import {chromium} from 'playwright';import {browserOptions} from '../support/browser.mjs';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const zh=JSON.parse(await fs.readFile('locales/zh-CN/common.json','utf8'));await fs.mkdir('test-results',{recursive:true});
function wav(freq){const samples=24000,buffer=Buffer.alloc(44+samples*2);buffer.write('RIFF');buffer.writeUInt32LE(buffer.length-8,4);buffer.write('WAVEfmt ',8);buffer.writeUInt32LE(16,16);buffer.writeUInt16LE(1,20);buffer.writeUInt16LE(1,22);buffer.writeUInt32LE(8000,24);buffer.writeUInt32LE(16000,28);buffer.writeUInt16LE(2,32);buffer.writeUInt16LE(16,34);buffer.write('data',36);buffer.writeUInt32LE(samples*2,40);for(let i=0;i<samples;i++)buffer.writeInt16LE(Math.round(Math.sin(i*freq*Math.PI*2/8000)*300),44+i*2);return buffer}
await fs.writeFile('test-results/studio-a.wav',wav(220));await fs.writeFile('test-results/studio-b.wav',wav(330));
const browser=await chromium.launch(browserOptions()),errors=[];let page;
try{const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173');
 await fs.copyFile(process.env.STUDIO_VIDEO||'test-results/studio-valid.webm','test-results/studio.webm');
 await page.locator('.studio-link').click();const dialog=page.getByRole('dialog');await dialog.getByLabel(zh['common.name'],{exact:true}).fill('雾港守灯人');await dialog.getByLabel(zh['creator.description'],{exact:true}).fill('守护雾港灯塔的记录员。');await dialog.getByLabel(zh['creator.greeting'],{exact:true}).fill('雾还没散，先坐下来喝杯茶吧。');
 await dialog.getByRole('button',{name:zh['creator.prompt'],exact:true}).click();await dialog.getByLabel(zh['creator.worldview'],{exact:true}).fill('雾港每个夜晚都由灯塔报时，居民用贝壳记录约定。');await dialog.getByLabel(zh['creator.systemPrompt'],{exact:true}).fill('语气克制，尊重玩家的决定。');
 await dialog.getByRole('button',{name:zh['creator.lore'],exact:true}).click();await dialog.getByLabel(zh['creator.bookName'],{exact:true}).fill('雾港手记');await dialog.getByRole('button',{name:zh['creator.addEntry'],exact:true}).click();await dialog.getByLabel(zh['lore.keys'],{exact:true}).fill('灯塔, 报时');await dialog.getByLabel(zh['lore.content'],{exact:true}).fill('灯塔每晚九点响三声。');
 await dialog.getByRole('button',{name:zh['creator.media'],exact:true}).click();await dialog.locator('input[type=file]').nth(0).setInputFiles(['public/icon-192.png','public/icon-512.png','test-results/studio.webm']);await dialog.locator('.studio-media-row').nth(2).waitFor();await dialog.locator('input[type=file]').nth(1).setInputFiles(['test-results/studio-a.wav','test-results/studio-b.wav']);await dialog.locator('.studio-media-row').nth(4).waitFor();await dialog.getByLabel(zh['creator.rotate'],{exact:true}).check();await dialog.getByLabel(zh['creator.interval'],{exact:true}).fill('5');await page.screenshot({path:'evidence/product/studio-desktop.png',fullPage:true});await page.setViewportSize({width:360,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'evidence/product/studio-mobile.png',fullPage:true});
 await dialog.getByRole('button',{name:zh['creator.save'],exact:true}).click();await dialog.waitFor({state:'hidden'});await page.locator('.provider-form select').first().selectOption('mock');await page.locator('.provider-form button[type=submit]').click();await page.locator('.enter-world button').click();await page.locator('.conversation-main').waitFor();
 const firstBg=await page.locator('.scene-backdrop img').getAttribute('src');await page.getByRole('button',{name:zh['media.nextBackground'],exact:true}).click();await page.waitForFunction(src=>document.querySelector('.scene-backdrop img')?.getAttribute('src')!==src,firstBg);await page.getByRole('button',{name:zh['media.nextBackground'],exact:true}).click();await page.locator('.scene-backdrop video').waitFor();await page.waitForFunction(()=>{const v=document.querySelector('.scene-backdrop video');return v&&v.readyState>=2&&v.videoWidth>0});const videoUrl=await page.locator('.scene-backdrop video').getAttribute('src');await page.waitForFunction(src=>document.querySelector('.scene-backdrop img, .scene-backdrop video')?.getAttribute('src')!==src,videoUrl,{timeout:12000});assert.equal(await page.locator('.music-player audio').evaluate(a=>a.paused),true);await page.getByRole('button',{name:zh['media.play'],exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.music-player audio').paused&&document.querySelector('.music-player audio').currentTime>0);const firstTrack=await page.locator('.music-player audio').getAttribute('src');await page.getByRole('button',{name:zh['media.nextTrack'],exact:true}).click();await page.waitForFunction(src=>document.querySelector('.music-player audio')?.getAttribute('src')!==src,firstTrack);await page.screenshot({path:'evidence/product/studio-playing-mobile.png',fullPage:true});
 await page.locator('.bottom-nav').getByRole('button',{name:zh['nav.settings'],exact:true}).click();await page.locator('.mobile-settings-view').getByRole('button',{name:zh['settings.data'],exact:true}).click();const downloading=page.waitForEvent('download');await page.locator('.mobile-settings-view').getByRole('button',{name:zh['settings.exportSave'],exact:true}).click();await (await downloading).saveAs('test-results/studio.ocwsave');const saved=JSON.parse(await fs.readFile('test-results/studio.ocwsave','utf8'));assert.equal(saved.character.design.backgroundIds.length,3);assert.equal(saved.character.design.musicIds.length,2);assert.equal(saved.assets.filter(a=>a.kind==='audio').length,2);const originalHash=saved.assets.find(a=>a.kind==='original').sha256;assert.equal(saved.worldbooks[0].entries[0].keys.length,2);assert.ok(saved.character.worldview.includes('贝壳'));
 await page.locator('.mobile-settings-view input[type=file]').setInputFiles('test-results/studio.ocwsave');await page.getByRole('status').waitFor();await page.locator('.bottom-nav').getByRole('button',{name:zh['nav.chat'],exact:true}).click();await page.locator('.music-player').waitFor();await page.reload();await page.locator('.conversation-main').waitFor();assert.equal(await page.locator('.music-player option').count(),2);assert.equal(await page.locator('.error-toast').count(),0);await page.locator('.bottom-nav').getByRole('button',{name:zh['nav.characters'],exact:true}).click();await page.getByRole('button',{name:zh['creator.edit'],exact:true}).click();await page.getByRole('dialog').getByLabel(zh['creator.description'],{exact:true}).fill('由玩家编辑后的守灯人设定。');await page.getByRole('dialog').getByRole('button',{name:zh['creator.save'],exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.locator('.bottom-nav').getByRole('button',{name:zh['nav.settings'],exact:true}).click();await page.locator('.mobile-settings-view').getByRole('button',{name:zh['settings.data'],exact:true}).click();const editedDownload=page.waitForEvent('download');await page.locator('.mobile-settings-view').getByRole('button',{name:zh['settings.exportSave'],exact:true}).click();await (await editedDownload).saveAs('test-results/studio-edited.ocwsave');const edited=JSON.parse(await fs.readFile('test-results/studio-edited.ocwsave','utf8'));assert.equal(edited.assets.find(a=>a.kind==='original').sha256,originalHash);assert.equal(edited.character.description,'由玩家编辑后的守灯人设定。');
 assert.deepEqual(errors,[]);await fs.writeFile('evidence/product/studio.json',JSON.stringify({manualCreation:true,promptAndWorldview:true,lorebookEntry:true,backgrounds:3,musicTracks:2,videoDecoded:true,originalPreservedAfterEdit:true,manualBackgroundSwitch:true,automaticRotation:true,musicStartsOnlyOnClick:true,trackSwitch:true,saveMediaRoundtrip:true,reload:true,mobile360:true,errors},null,2));
}catch(e){if(page){await page.screenshot({path:'test-results/studio-failure.png',fullPage:true});console.error((await page.locator('body').innerText()).slice(-2200));console.error(await page.evaluate(()=>({hidden:document.hidden,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,media:[...document.querySelectorAll('video,audio')].map(v=>({tag:v.tagName,ready:v.readyState,error:v.error?.message,time:v.currentTime,paused:v.paused}))})))}throw e}finally{await browser.close()}
