import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {pluginSchema,type WritingSettings} from '../domain/writing.ts';
import {run,patchApp} from '../app/store.ts';
import {download} from '../app/service.ts';
export function AdvancedWriting({draft,change}:{draft:WritingSettings;change:(value:Partial<WritingSettings>)=>void}){
 const {t}=useTranslation(),[preview,setPreview]=useState('');
 return <details className="advanced-writing"><summary>{t('advanced.title')}</summary>
 <h3>{t('advanced.macros')}</h3><label><input type="checkbox" checked={draft.macrosEnabled??false} onChange={e=>change({macrosEnabled:e.target.checked})}/>{t('advanced.macrosEnable')}</label><p className="hint">{t('advanced.macrosHint')}</p>
 {Object.entries(draft.variables??{}).map(([key,value])=><label key={key}>{key}<input aria-label={key} maxLength={2000} value={value} onChange={e=>change({variables:{...draft.variables,[key]:e.target.value}})}/><button type="button" onClick={()=>{const next={...draft.variables};delete next[key];change({variables:next})}}>{t('common.delete')}</button></label>)}
 <button type="button" className="button secondary" disabled={Object.keys(draft.variables??{}).length>=50} onClick={()=>{let i=1;while(Object.hasOwn(draft.variables??{},'var'+i))i++;change({variables:{...draft.variables,['var'+i]:''}})}}>{t('advanced.addVariable')}</button>
 <label>{t('advanced.preview')}<textarea aria-label={t('advanced.preview')} maxLength={65536} value={preview} onChange={e=>setPreview(e.target.value)}/></label><button className="button secondary" type="button" onClick={()=>void run(async()=>{const {renderProgram}=await import('../context/program.ts');setPreview(renderProgram(preview,draft.variables))})}>{t('advanced.runPreview')}</button>
 <pre className="hint">{'{{setvar::tone::quiet}}\n{{#if::tone::quiet}}简短回应{{else}}详细回应{{/if}}\n{{#repeat::3}}{{index}}{{/repeat}}'}</pre><h3>{t('advanced.plugins')}</h3><p className="hint">{t('advanced.pluginHint')}</p>
 <a className="button secondary" href={new URL('../../examples/quiet-narration.ocw-plugin.json',import.meta.url).href} download="quiet-narration.ocw-plugin.json">{t('advanced.sample')}</a><label className="button secondary file-button">{t('advanced.install')}<input type="file" accept=".json" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void run(async()=>{if(file.size>256*1024)throw Error('fileTooLarge');let plugin;try{plugin=pluginSchema.parse(JSON.parse(await file.text()))}catch{throw Error('invalidPlugin')}if((draft.plugins??[]).length>=8||(draft.plugins??[]).some(p=>p.id===plugin.id))throw Error('pluginDuplicate');change({plugins:[...(draft.plugins??[]),{...plugin,enabled:false}]})})}}/></label>
 {(draft.plugins??[]).map((plugin,index)=><section className="writing-quick-row" key={plugin.id}><label><input type="checkbox" checked={plugin.enabled} onChange={e=>change({plugins:draft.plugins.map((p,i)=>i===index?{...p,enabled:e.target.checked}:p)})}/>{plugin.name}</label><small>{plugin.license} · {plugin.source}</small><details><summary>{t('advanced.inspect')}</summary><pre>{plugin.licenseText}</pre><pre>{plugin.code}</pre></details><div className="form-actions"><button type="button" onClick={()=>download(new Blob([JSON.stringify({...plugin,enabled:false},null,2)],{type:'application/json'}),plugin.id+'.json')}>{t('advanced.exportPlugin')}</button><button type="button" onClick={()=>change({plugins:draft.plugins.filter(p=>p.id!==plugin.id)})}>{t('common.delete')}</button></div></section>)}
 <h3>{t('advanced.vectors')}</h3><label><input type="checkbox" checked={draft.vectorsEnabled??false} onChange={e=>change({vectorsEnabled:e.target.checked})}/>{t('advanced.vectorsEnable')}</label><p className="hint">{t('advanced.vectorsHint')}</p><label><input type="checkbox" checked={draft.vectorDialogue??false} onChange={e=>change({vectorDialogue:e.target.checked})}/>{t('advanced.dialogue')}</label><p className="hint">{t('advanced.docsHint')}</p><label className="button secondary file-button">{t('advanced.importDoc')}<input type="file" accept=".txt,.md" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void run(async()=>{if(file.size>64*1024)throw Error('fileTooLarge');if(!/\.(txt|md)$/i.test(file.name))throw Error('invalidMemoryDoc');const text=await file.text();if(text.length>16000||!text.trim()||(draft.memoryDocs??[]).length>=8)throw Error('invalidMemoryDoc');change({memoryDocs:[...(draft.memoryDocs??[]),{id:crypto.randomUUID(),name:file.name.slice(0,100),text,enabled:true}]})})}}/></label>{(draft.memoryDocs??[]).map((doc,index)=><section className="writing-quick-row" key={doc.id}><label><input type="checkbox" checked={doc.enabled} onChange={e=>change({memoryDocs:draft.memoryDocs.map((d,i)=>i===index?{...d,enabled:e.target.checked}:d)})}/>{doc.name}</label><details><summary>{t('advanced.docText')}</summary><textarea aria-label={doc.name} maxLength={16000} value={doc.text} onChange={e=>change({memoryDocs:draft.memoryDocs.map((d,i)=>i===index?{...d,text:e.target.value}:d)})}/></details><button type="button" onClick={()=>change({memoryDocs:draft.memoryDocs.filter(d=>d.id!==doc.id)})}>{t('common.delete')}</button></section>)}<label>{t('advanced.embeddingModel')}<input aria-label={t('advanced.embeddingModel')} value={draft.embeddingModel??''} maxLength={200} required={draft.vectorsEnabled} onChange={e=>change({embeddingModel:e.target.value})}/></label><button type="button" className="button secondary" onClick={()=>void run(async()=>{const {clearVectorCache}=await import('../app/retrieval.ts');await clearVectorCache();patchApp({notice:'saved'})})}>{t('advanced.clearIndex')}</button>
 </details>
}
