const WritingPanel=lazy(()=>import('./WritingPanel.tsx').then(m=>({default:m.WritingPanel})));
import {expandMacros} from '../context/macros.ts';
import {GroupPanel} from './GroupPanel.tsx';
import {holderOf,itemLocation} from '../runtime/possession.ts';
import {Creator} from './Creator.tsx';
import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {useApp,patchApp,run,reportError} from '../app/store.ts';
import {initialize,example,importCard,newChat,selectChat,renameChat,sendGroupMessage,sendMessage,cancelGeneration,regenerate,continueReply,editMessage,deleteMessage,swipeMessage,branchChat,structuredAction,updateSettings} from '../app/service.ts';
import {BRAND} from '../app/brand.ts';
import type {Message,Candidate} from '../domain/types.ts';
import i18n from '../i18n/index.ts';
import {SceneRenderer,displayName} from '../scene/SceneRenderer.tsx';
import {Avatar,Icon,Modal,Empty} from './primitives.tsx';
import {ProviderForm} from './ProviderForm.tsx';
import {WorldPanel,SettingsPanel,PersonaPanel,LorePanel,ContextPanel,CharacterPanel,HelpPanel,Tutorial} from './panels.tsx';
type Panel='settings'|'characters'|'persona'|'lore'|'context'|'character'|'help'|'writing';
export default function App(){
 const {t}=useTranslation(),s=useApp(),[creator,setCreator]=useState<{id?:string}>(),[panel,setPanel]=useState<Panel>(),[worldOpen,setWorldOpen]=useState(false),[sidebar,setSidebar]=useState(true),[mobileTab,setMobileTab]=useState('chat'),[input,setInput]=useState(''),[action,setAction]=useState<string>(),[chosen,setChosen]=useState(''),[editing,setEditing]=useState<{message:Message;operation:'edit'|'delete'|'swipe';index?:number}>(),[editText,setEditText]=useState(''),[renaming,setRenaming]=useState(false),[chatName,setChatName]=useState('');
 const fileInput=useRef<HTMLInputElement>(null),composer=useRef<HTMLTextAreaElement>(null),scroll=useRef<HTMLDivElement>(null);
 const character=s.characters.find(c=>c.id===s.selectedCharacterId),chat=s.chats.find(c=>c.id===s.activeChatId),world=s.world;
 useEffect(()=>{void initialize().catch(e=>{reportError(e);patchApp({ready:true})})},[]);
 useEffect(()=>{void i18n.changeLanguage(s.settings.language);document.documentElement.lang=s.settings.language;document.documentElement.dataset.theme=s.settings.theme;document.documentElement.dataset.performance=s.settings.performance;document.documentElement.dataset.motion=String(s.settings.motion);document.title=BRAND.name},[s.settings]);
 useEffect(()=>{if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight},[s.messages,s.streamText,s.ready,s.route,s.activeChatId]);
 useEffect(()=>{if(!s.notice)return;const timer=setTimeout(()=>patchApp({notice:undefined}),5000);return()=>clearTimeout(timer)},[s.notice]);
 const pickFile=(file?:File)=>{if(file)void run(async()=>{await importCard(file);setPanel(undefined);setMobileTab('chat')})};
 const toggleLanguage=()=>void run(()=>updateSettings({...s.settings,language:s.settings.language==='zh-CN'?'en-US':'zh-CN'}));
 const send=()=>{const value=input;if(!value.trim()||s.sending)return;setInput('');void run(()=>sendMessage(value))};
 const currentName=(name:string)=>displayName(name,s.settings.language);
 const openEdit=(message:Message,operation:'edit'|'delete'|'swipe',index?:number)=>{setEditing({message,operation,index});setEditText(message.content)};
 const chooseAction=(kind:string)=>{if(kind==='talk'){composer.current?.focus();return}if(kind==='ask'){setInput(t('action.askPrompt'));composer.current?.focus();return}if(kind==='observe'){void run(()=>sendMessage(t('action.observePrompt')));return}setAction(kind);setChosen('')};
 const executeAction=async()=>{if(!world||!character||!action)return;const item=world.entities[chosen];let fields:Partial<Candidate>,label:string;
  if(action==='invite'){fields={kind:'ACCEPT_INVITATION',target:character.id,text:chosen,requiresConsent:true};label=chosen}
  else if(action==='wait'){fields={kind:'TIME_ADVANCE',minutes:Number(chosen)};label=t('action.waitText',{minutes:Number(chosen)})}
  else if(action==='store'||action==='return'){fields={kind:action==='store'?'STORE_ITEM':'RETURN_ITEM',entityId:chosen,target:character.id,requiresConsent:true};label=t('action.'+action+'Text',{item:currentName(item.name)})}
  else if(action==='give'){fields={kind:'TRANSFER_ITEM',entityId:chosen,target:character.id,requiresConsent:true};label=t('action.giveText',{item:currentName(item.name)})}
  else if(action==='use'){const door=Object.values(world.entities).find(e=>e.keyId===chosen&&e.locked);fields={kind:'USE_ITEM',entityId:chosen,destination:door?.id};label=t('action.useText',{item:currentName(item.name)})}
  else if(action==='drop'||action==='take'){fields={kind:action==='drop'?'DROP_ITEM':'TAKE_ITEM',entityId:chosen};label=t('action.'+action)+' '+currentName(item.name)}
  else{fields={kind:'MOVE',destination:chosen};label=t('action.moveText',{place:currentName(item.name)})}setAction(undefined);await structuredAction(fields.kind!,fields,label);
 };
 const characterPicker=<div className="character-picker"><button className="button primary creator-entry" type="button" disabled={s.sending} onClick={()=>setCreator({})}><Icon name="plus"/>{t('creator.new')}</button><label className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();pickFile(e.dataTransfer.files[0])}}><Icon name="upload"/><strong>{t('wizard.drop')}</strong><span>{t('wizard.formats')}</span><button className="button secondary" type="button" onClick={()=>fileInput.current?.click()}>{t('wizard.browse')}</button><small>{t('wizard.original')}</small></label><button className="text-button" onClick={()=>void run(example)}>{t('landing.example')} →</button>{s.characters.map(c=><button key={c.id} className={`character-choice ${s.selectedCharacterId===c.id?'selected':''}`} onClick={()=>patchApp({selectedCharacterId:c.id})}><Avatar character={c}/><span><strong>{currentName(c.name)}</strong><small>{c.creator}</small></span>{s.selectedCharacterId===c.id&&<Icon name="check"/>}</button>)}</div>;
 const modalTitles:Record<Panel,string>={settings:'settings.title',characters:'nav.characters',persona:'persona.title',lore:'lore.title',context:'context.title',character:'character.title',help:'help.title',writing:'writing.title'};
 if(!s.ready)return <div className="loading-screen"><Icon name="spark"/><p>{t('common.loading')}</p></div>;
 return <div className={`app route-${s.route}`}>
 <input ref={fileInput} hidden type="file" accept=".png,.json,.charx,.webp" aria-label={t('landing.import')} onChange={e=>{pickFile(e.target.files?.[0]);e.target.value=''}}/>
 <header className="topbar"><button className="brand" onClick={()=>{if(!s.sending)patchApp({route:'landing'})}} aria-label={t('nav.home')}><span className="brand-mark"><Icon name="spark"/></span><span className="brand-full">{BRAND.name}</span><span className="brand-short">{BRAND.shortName}</span></button><nav>{s.updateReady&&<button className="update-button" disabled={s.sending} onClick={()=>window.dispatchEvent(new Event('oc-apply-update'))}>{t('common.update')}</button>}<button className="studio-link" aria-label={t('creator.new')} disabled={s.sending} onClick={()=>setCreator({})}><Icon name="plus"/><span>{t('creator.new')}</span></button>{s.route==='play'&&<><span className="save-status"><i/>{s.sending?t('chat.thinking'):t('chat.saved')}</span><button className={`world-toggle ${worldOpen?'active':''}`} onClick={()=>setWorldOpen(!worldOpen)}><Icon name="world"/>{t('world.title')}</button></>}<button className="language-button" onClick={toggleLanguage} aria-label={t('settings.language')}>{s.settings.language==='zh-CN'?'EN':'中文'}</button><button className="icon-button" aria-label={t('nav.help')} onClick={()=>setPanel('help')}><Icon name="help"/></button><button className="icon-button" aria-label={t('nav.settings')} onClick={()=>setPanel('settings')}><Icon name="settings"/></button></nav></header>
 {s.route==='landing'&&<main className="landing"><section className="landing-hero"><div className="hero-art"><img className="hero-background" src="/archive.png" alt=""/><img className="hero-character" src="/eileen.png" alt="Eileen"/></div><div className="hero-copy"><span className="eyebrow"><span className="tiny-star">✧</span>{t('landing.eyebrow')}</span><h1>{t('landing.title')}</h1><p>{t('landing.subtitle')}</p><div className="hero-buttons"><button className="button primary" onClick={()=>patchApp({route:'wizard',wizardStep:1})}>{t('landing.start')}<Icon name="arrow"/></button><button className="button ghost" onClick={()=>void run(example)}>{t('landing.example')}</button></div><button className="text-button hero-import" onClick={()=>fileInput.current?.click()}><Icon name="upload"/>{t('landing.import')}</button></div><div className="hero-footnote"><span>01 /</span><span>{t('wizard.ready')}</span></div></section><section className="landing-values">{[['local','lock'],['own','spark'],['compat','book']].map(([id,icon])=><article key={id}><Icon name={icon}/><h2>{t('landing.'+id)}</h2><p>{t('landing.'+id+'Body')}</p></article>)}</section><footer><span>{BRAND.shortName} · {BRAND.version}</span><p>{t('landing.privacy')}</p></footer></main>}
 {s.route==='wizard'&&<main className="wizard"><button className="text-button" onClick={()=>patchApp({route:s.activeChatId?'play':'landing'})}>← {t('common.back')}</button><span className="eyebrow">{BRAND.shortName}</span><h1>{t('wizard.title')}</h1><div className="wizard-steps">{['character','model','enter'].map((key,index)=><button key={key} disabled={index+1>s.wizardStep} className={s.wizardStep===index+1?'active':''} onClick={()=>patchApp({wizardStep:index+1})}><span>{index+1}</span>{t('wizard.'+key)}</button>)}</div><section className="wizard-content">{s.wizardStep===1&&<>{characterPicker}{character&&<div className="import-preview"><Avatar character={character} large/><h2>{currentName(character.name)}</h2><p>{character.description.slice(0,260)}</p>{character.compatibilityWarnings?.map(w=><p className="callout" key={w}>{t('compat.'+w)}</p>)}<div className="tags"><span>{t('wizard.greetings',{count:character.greetings.length})}</span><span>{t('wizard.books',{count:character.worldbookIds.length})}</span><span>{character.sourceSpec.toUpperCase()}</span></div><button className="button primary" onClick={()=>patchApp({wizardStep:2})}>{t('common.continue')}<Icon name="arrow"/></button></div>}</>}{s.wizardStep===2&&<ProviderForm onSaved={()=>patchApp({wizardStep:3})}/>} {s.wizardStep===3&&character&&<div className="enter-world"><Avatar character={character} large/><span className="eyebrow">{t('wizard.ready')}</span><h2>{currentName(character.name)}</h2><p>{character.scenario}</p><button className="button primary" onClick={()=>void run(()=>newChat(character.id))}>{t('wizard.enter')}<Icon name="arrow"/></button></div>}</section></main>}
 {s.route==='play'&&character&&world&&<div className={`play-layout ${worldOpen?'world-open':''} ${sidebar?'':'sidebar-closed'} mobile-${mobileTab}`}>
 <aside className="character-sidebar"><div className="sidebar-character"><Avatar character={character} large/><h2>{currentName(character.name)}</h2><p>{currentName(world.entities[world.location]?.name??'')}</p></div><button className="button secondary" disabled={s.sending} onClick={()=>void run(()=>newChat(character.id))}><Icon name="plus"/>{t('chat.new')}</button><div className="section-label">{t('chat.sessions')}</div><div className="session-list">{s.chats.filter(c=>c.characterId===character.id).map(c=><button key={c.id} disabled={s.sending} className={c.id===s.activeChatId?'active':''} onClick={()=>void run(()=>selectChat(c.id))}><Icon name="chat"/><span>{c.name}</span></button>)}</div><div className="sidebar-tools"><button disabled={s.sending} onClick={()=>setCreator({id:character.id})}><Icon name="spark"/>{t('creator.edit')}</button><button onClick={()=>setPanel('characters')}><Icon name="user"/>{t('character.switch')}</button><button onClick={()=>setPanel('character')}><Icon name="book"/>{t('character.title')}</button>{s.settings.mode!=='simple'&&<><button onClick={()=>setPanel('persona')}><Icon name="user"/>{t('persona.title')}</button><button onClick={()=>setPanel('lore')}><Icon name="book"/>{t('lore.title')}</button></>}{s.settings.mode==='expert'&&<button onClick={()=>setPanel('context')}><Icon name="eye"/>{t('context.title')}</button>}</div></aside>
 <main className="conversation-main"><div className="conversation-heading"><button className="icon-button sidebar-control" onClick={()=>setSidebar(!sidebar)} aria-label={t(sidebar?'nav.hideSidebar':'nav.showSidebar')}><Icon name="menu"/></button><button className="chat-name" onClick={()=>{setChatName(chat?.name??'');setRenaming(true)}}>{chat?.name}<span>⌄</span></button>{s.provider.kind==='mock'&&<span className="demo-label">{t('provider.demo')}</span>}</div><SceneRenderer character={character} world={world} settings={s.settings} expression={s.expression}/>
 <div className="conversation-scroll" ref={scroll}>{s.messages.length?s.messages.map((m,index)=><article className={`message ${m.role}`} key={m.id} data-testid={`message-${m.role}`}><div className="message-avatar">{m.role==='assistant'?<Avatar character={s.characters.find(c=>c.id===m.speakerId)??character}/>:<span className="player-avatar"><Icon name="user"/></span>}</div><div className="message-body"><div className="message-meta"><strong>{m.role==='assistant'?currentName(s.characters.find(c=>c.id===m.speakerId)?.name??character.name):t('chat.you')}</strong><time>{new Date(m.createdAt).toLocaleTimeString(s.settings.language,{hour:'2-digit',minute:'2-digit'})}</time><details className="message-tools" name="message-actions" onClick={e=>{if((e.target as HTMLElement).closest('button'))e.currentTarget.open=false}} onKeyDown={e=>{if(e.key==='Escape')e.currentTarget.open=false}}><summary aria-label={t('chat.actions')}><Icon name="more"/></summary><div>{m.role==='assistant'&&s.messages.slice(0,index).some(x=>x.role==='user')&&<button disabled={s.sending} onClick={()=>void run(()=>regenerate(m.id))}>{t('chat.regenerate')}</button>}<button disabled={s.sending} onClick={()=>openEdit(m,'edit')}>{t('common.edit')}</button><button disabled={s.sending} onClick={()=>openEdit(m,'delete')}>{t('common.delete')}</button><button onClick={()=>void run(async()=>{await navigator.clipboard.writeText(m.content);patchApp({notice:'copied'})})}>{t('common.copy')}</button><button disabled={s.sending} onClick={()=>void run(()=>branchChat(m.id))}>{t('chat.branch')}</button></div></details></div><div className="message-content">{m.content}</div>{m.status==='interrupted'&&<small className="interrupted">{t('chat.interrupted')}</small>}{m.role==='assistant'&&m.variants.length>1&&<div className="swipe"><button disabled={s.sending||m.selected===0} onClick={()=>openEdit(m,'swipe',m.selected-1)} aria-label={t('chat.previous')}>‹</button><span>{t('chat.variant',{index:m.selected+1,count:m.variants.length})}</span><button disabled={s.sending||m.selected===m.variants.length-1} onClick={()=>openEdit(m,'swipe',m.selected+1)} aria-label={t('chat.next')}>›</button></div>}</div></article>):<Empty text={t('chat.empty')}/>}{s.sending&&<article className="message assistant streaming"><div className="message-avatar"><Avatar character={s.characters.find(c=>c.id===s.speakingCharacterId)??character}/></div><div className="message-body"><div className="message-meta"><strong>{currentName(s.characters.find(c=>c.id===s.speakingCharacterId)?.name??character.name)}</strong><span className="typing-dots">•••</span></div><div className="message-content">{s.streamText.replace(/^\[expression:\w+\]\s*/,'')||t('chat.thinking')}<span className="cursor"/></div></div></article>}</div>
 <div className="composer-area"><button className="text-button writing-open" disabled={s.sending} onClick={()=>setPanel('writing')}>{t('writing.title')}</button><GroupPanel/>{!!chat?.writing?.quickReplies.length&&<div className="quick-replies">{chat.writing.quickReplies.map((q,i)=><button key={i} disabled={s.sending} title={q.text} onClick={()=>void run(async()=>{setInput(expandMacros(q.text,character,world,s.personas.find(p=>p.id===chat.personaId),chat.writing?.scenarioEnabled!==false&&chat.writing?.scenario.trim()?chat.writing.scenario:character.scenario,chat.writing));composer.current?.focus()})}>{q.label}</button>)}</div>}<div className="quick-actions">{[['talk','chat'],['ask','help'],['observe','eye'],['give','gift'],['store','gift'],['return','gift'],['use','spark'],['invite','user'],['follow','arrow'],['leave','arrow'],['take','gift'],['drop','gift'],['wait','moon']].map(([key,icon])=><button key={key} disabled={s.sending||(['give','store','return','invite'].includes(key)&&!world.participants.includes(character.id))||(key==='follow'&&world.participants.includes(character.id))||(['give','store','drop'].includes(key)&&!Object.values(world.entities).some(e=>e.type==='item'&&holderOf(world,e)==='player'&&!e.consumed))||(key==='take'&&!Object.values(world.entities).some(e=>e.type==='item'&&!holderOf(world,e)&&(!e.owner||e.owner==='player')&&!e.consumed&&itemLocation(world,e)===world.location))||(key==='use'&&!Object.values(world.entities).some(e=>e.owner==='player'&&holderOf(world,e)==='player'&&e.usable&&!e.consumed))} onClick={()=>chooseAction(key)}><Icon name={icon}/>{t('action.'+key)}</button>)}</div><div className="composer"><textarea ref={composer} rows={2} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}} placeholder={t('chat.placeholder')} aria-label={t('chat.placeholder')}/>{s.sending?<button className="send-button stop" aria-label={t('chat.stop')} onClick={cancelGeneration}>■</button>:<button className="send-button" disabled={!input.trim()} aria-label={t('chat.send')} onClick={send}><Icon name="send"/></button>}</div><div className="composer-foot">{(chat?.memberIds?.length??0)>1&&<button disabled={s.sending||!input.trim()} onClick={()=>{const text=input;setInput('');void run(()=>sendGroupMessage(text))}}>{t('group.round')}</button>}<span><i/>{s.provider.kind==='mock'?t('provider.demo'):s.provider.model}</span><button disabled={s.sending||!s.messages.length} onClick={()=>void run(continueReply)}>{t('chat.continue')} ↗</button></div></div></main>
 <aside className="desktop-world"><WorldPanel/></aside><section className="mobile-world-view"><WorldPanel key={mobileTab} tab={mobileTab==='events'?'events':'world'}/></section><section className="mobile-character-view"><div className="mobile-card"><Avatar character={character} large/><h2>{currentName(character.name)}</h2><button className="button secondary" onClick={()=>setPanel('characters')}>{t('character.switch')}</button><button className="button secondary" onClick={()=>void run(()=>newChat(character.id))}>{t('chat.new')}</button><button className="button secondary" disabled={s.sending} onClick={()=>setCreator({id:character.id})}>{t('creator.edit')}</button><CharacterPanel/></div></section><section className="mobile-settings-view"><SettingsPanel/></section>
 <nav className="bottom-nav">{[['chat','chat'],['characters','user'],['world','world'],['events','book'],['settings','settings']].map(([key,icon])=><button key={key} className={mobileTab===key?'active':''} onClick={()=>setMobileTab(key)}><Icon name={icon}/><span>{t('nav.'+key)}</span></button>)}</nav></div>}
 {creator&&<Modal title={t(creator.id?'creator.edit':'creator.new')} onClose={()=>setCreator(undefined)} wide><Creator characterId={creator.id} onSaved={c=>{setCreator(undefined);setPanel(undefined);if(s.route!=='play'||c.id!==s.selectedCharacterId)patchApp({route:'wizard',wizardStep:2,selectedCharacterId:c.id})}}/></Modal>}
 {panel&&<Modal title={t(modalTitles[panel])} onClose={()=>setPanel(undefined)} wide={panel==='context'}>{panel==='settings'?<SettingsPanel/>:panel==='persona'?<PersonaPanel/>:panel==='lore'?<LorePanel/>:panel==='context'?<ContextPanel/>:panel==='character'?<CharacterPanel/>:panel==='help'?<HelpPanel/>:panel==='writing'&&s.activeChatId?<Suspense fallback={<p>{t('common.loading')}</p>}><WritingPanel chatId={s.activeChatId} onSaved={()=>setPanel(undefined)}/></Suspense>:<>{characterPicker}{character&&<button className="button primary" disabled={s.sending} onClick={()=>void run(async()=>{await newChat(character.id);setPanel(undefined);setMobileTab('chat')})}>{t('wizard.enter')}</button>}</>}</Modal>}
 {editing&&<Modal title={t(editing.operation==='delete'?'common.delete':'common.edit')} onClose={()=>setEditing(undefined)}><p className="callout">{t('chat.editWarning')}</p>{editing.operation==='edit'&&<textarea rows={8} value={editText} onChange={e=>setEditText(e.target.value)} aria-label={t('common.edit')}/>}<div className="form-actions"><button className="button secondary" onClick={()=>setEditing(undefined)}>{t('common.cancel')}</button><button className="button primary" onClick={()=>void run(async()=>{if(editing.operation==='edit')await editMessage(editing.message.id,editText);else if(editing.operation==='delete')await deleteMessage(editing.message.id);else await swipeMessage(editing.message.id,editing.index!);setEditing(undefined)})}>{t('common.confirm')}</button></div></Modal>}
 {renaming&&<Modal title={t('chat.rename')} onClose={()=>setRenaming(false)}><form onSubmit={e=>{e.preventDefault();void run(async()=>{await renameChat(s.activeChatId!,chatName);setRenaming(false)})}}><label>{t('common.name')}<input value={chatName} onChange={e=>setChatName(e.target.value)} required/></label><button className="button primary">{t('common.save')}</button></form></Modal>}
 {action&&world&&<Modal title={t('action.'+action)} onClose={()=>setAction(undefined)}><Tutorial name="action"/><form onSubmit={e=>{e.preventDefault();void run(executeAction)}}>{action==='invite'?<label>{t('action.invitePrompt')}<textarea required maxLength={300} rows={3} value={chosen} onChange={e=>setChosen(e.target.value)}/></label>:action==='wait'?<label>{t('action.wait')}<select required value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">—</option>{[15,30,60].map(n=><option key={n} value={n}>{t('action.waitText',{minutes:n})}</option>)}</select></label>:<label>{t(['give','store','return','use','take','drop'].includes(action)?'action.chooseItem':'action.choosePlace')}<select value={chosen} onChange={e=>setChosen(e.target.value)} required><option value="">—</option>{Object.values(world.entities).filter(e=>['give','store','use','drop'].includes(action)?e.type==='item'&&holderOf(world,e)==='player'&&!e.consumed&&(action!=='use'||e.usable):action==='return'?e.type==='item'&&!e.consumed&&((e.owner==='player'&&holderOf(world,e)===character!.id)||(e.owner===character!.id&&holderOf(world,e)==='player')):action==='take'?e.type==='item'&&!holderOf(world,e)&&(!e.owner||e.owner==='player')&&itemLocation(world,e)===world.location:e.type==='place'&&e.id!==world.location&&!e.locked&&(action!=='follow'||e.id===world.entities[character!.id].location)).map(e=><option key={e.id} value={e.id}>{currentName(e.name)}</option>)}</select></label>}<button className="button primary" disabled={!chosen||s.sending}>{t('common.confirm')}</button></form></Modal>}
 {s.error&&<div role="alert" className="error-toast"><div><strong>{t('error.'+s.error.code,{defaultValue:t('error.unknown')})}</strong>{s.settings.mode==='expert'&&s.error.detail&&<details><summary>{t('error.raw')}</summary><pre>{s.error.detail}</pre></details>}</div><button className="icon-button" aria-label={t('common.close')} onClick={()=>patchApp({error:undefined})}><Icon name="close"/></button></div>}{s.notice&&<div role="status" className="notice-toast"><Icon name="check"/>{t('notice.'+s.notice,{defaultValue:t('notice.saved')})}</div>}
 </div>;
}
