import {holderOf,itemLocation} from '../runtime/possession.ts';
import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {useApp,patchApp,run} from '../app/store.ts';
import {updateSettings,download,selectChat,exportOriginal,refresh} from '../app/service.ts';
import {atmosphere,setBackground,setExpressionAsset,savePersona,decidePending,defineItem} from '../app/author.ts';
import {importWorldbook} from '../compatibility/character.ts';
import {exportSave,importSave,exportChat} from '../storage/save-client.ts';
import {books,requestPersistence} from '../storage/db.ts';
import type {WorldEvent,Particle,Expression,Settings} from '../domain/types.ts';
import {displayName} from '../scene/SceneRenderer.tsx';
import {ProviderForm} from './ProviderForm.tsx';
import {Icon,Empty} from './primitives.tsx';
export function Tutorial({name}:{name:'world'|'event'|'action'}){const {t}=useTranslation(),settings=useApp(s=>s.settings);if(settings.tutorialDismissed.includes(name))return null;return <aside className="tutorial"><Icon name="spark"/><div><p>{t('onboard.'+name)}</p><button className="text-button" onClick={()=>void run(()=>updateSettings({...settings,tutorialDismissed:[...settings.tutorialDismissed,name]}))}>{t('onboard.dismiss')}</button></div></aside>}
export function WorldPanel({tab:initial='world'}:{tab?:'world'|'events'|'facts'|'relationships'}){
 const {t}=useTranslation(),state=useApp(),[tab,setTab]=useState(initial),[itemName,setItemName]=useState('');const world=state.world;if(!world)return null;
 const name=(id?:string)=>displayName(world.entities[id??'']?.name??id??'',state.settings.language),items=Object.values(world.entities).filter(e=>e.type==='item');
 const describe=(e:WorldEvent)=>t('event.'+e.event_type,{actor:displayName(e.details.actor,state.settings.language),target:displayName(e.details.target??'',state.settings.language),item:displayName(e.details.entity??'',state.settings.language),place:displayName(e.details.destination??'',state.settings.language),text:e.details.text??''});
 return <div className="world-panel"><div className="panel-title"><span className="eyebrow">{t('world.title')}</span><Icon name="world"/></div><div className="tabs">{(['world','events','facts','relationships'] as const).map(id=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{t(id==='world'?'nav.world':'world.'+id)}</button>)}</div><Tutorial name="world"/>
 {tab==='world'&&<><div className="world-location"><Icon name="moon"/><h3>{name(world.location)}</h3><p>{t('world.day',{day:world.day})} · {Math.floor(world.minutes/60)}:{String(world.minutes%60).padStart(2,'0')} · {t('visual.'+world.weather)}</p></div><h4>{t('world.present')}</h4><div className="tags">{world.participants.map(id=><span key={id}>{id==='player'?t('chat.you'):name(id)}</span>)}</div><h4>{t('world.inventory')}</h4>{items.length?items.map(item=><div className="fact-row" key={item.id}><Icon name="gift"/><div><strong>{name(item.id)}</strong><small>{t('world.owner')} · {item.owner?item.owner==='player'?t('chat.you'):name(item.owner):t('common.none')}</small><small>{t('world.holder')} · {name(holderOf(world,item))||t('world.ground')} · {t('world.location')} · {name(itemLocation(world,item))}</small></div>{item.consumed&&<small>{t('common.none')}</small>}</div>):<Empty text={t('action.noItems')}/>}</>}
 {tab==='events'&&<>{state.events.length>0&&<Tutorial name="event"/>}{state.events.length?<div className="timeline">{[...state.events].reverse().map(e=><article key={e.id}><small>{t('world.day',{day:e.world_time.day})} · {Math.floor(e.world_time.minutes/60)}:{String(e.world_time.minutes%60).padStart(2,'0')}</small><p>{describe(e)}</p></article>)}</div>:<Empty text={t('world.noEvents')}/>}</>}
 {tab==='facts'&&<>{Object.values(world.entities).map(e=><article className="entity-fact" key={e.id}><h4>{name(e.id)}</h4>{e.description&&<p>{e.description}</p>}{e.owner&&<div>{t('world.owner')}<strong>{name(e.owner)}</strong></div>}{e.type==='item'&&<div>{t('world.holder')}<strong>{name(holderOf(world,e))||t('world.ground')}</strong></div>}{e.location&&<div>{t('world.location')}<strong>{name(e.type==='item'?itemLocation(world,e):e.location)}</strong></div>}{e.alive!==undefined&&<div>{t('fact.alive')}<strong>{t(e.alive?'common.yes':'common.no')}</strong></div>}{e.locked!==undefined&&<div>{t('fact.locked')}<strong>{t(e.locked?'common.yes':'common.no')}</strong></div>}</article>)}{state.settings.mode==='expert'&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{await defineItem(itemName,'');setItemName('')})}}><p className="hint">{t('world.authorNotice')}</p><label>{t('world.addItem')}<input required maxLength={100} value={itemName} onChange={e=>setItemName(e.target.value)}/></label><button className="button secondary" disabled={state.sending}>{t('common.confirm')}</button></form>}</>}
 {tab==='relationships'&&<div className="relationship"><Icon name="user"/>{Object.entries(world.relationships).map(([id,level])=><div key={id}><h3>{name(id)}</h3><span className="tag">{t('world.'+level)}</span></div>)}</div>}
 {state.transactions.some(tx=>tx.status==='pending')&&<div className="pending-list"><h4>{t('world.pending')}</h4><p className="hint">{t('world.pendingHint')}</p>{state.transactions.filter(tx=>tx.status==='pending').map(tx=><div key={tx.id}><p>{tx.text??(tx.entityId?name(tx.entityId):t('world.pending'))}</p>{state.settings.mode==='expert'&&<button className="text-button" disabled={state.sending} onClick={()=>void run(()=>decidePending(tx.id,true))}>{t('world.accept')}</button>}<button className="text-button" disabled={state.sending} onClick={()=>void run(()=>decidePending(tx.id,false))}>{t('common.cancel')}</button></div>)}</div>}
 </div>;
}
export function SettingsPanel(){
 const {t}=useTranslation(),state=useApp(),settings=state.settings,[section,setSection]=useState('general');const change=(key:keyof Settings,value:unknown)=>void run(()=>updateSettings({...settings,[key]:value}));
 return <><div className="tabs">{['general','provider','visual','data'].map(id=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{t(id==='provider'?'provider.title':'settings.'+id)}</button>)}</div>
 {section==='general'&&<div className="settings-fields"><label>{t('settings.language')}<select value={settings.language} onChange={e=>change('language',e.target.value)}><option value="zh-CN">简体中文</option><option value="en-US">English</option></select></label><p className="hint">{t('settings.contentLanguage')}</p><label>{t('settings.theme')}<select value={settings.theme} onChange={e=>change('theme',e.target.value)}>{['dark','light','system'].map(v=><option key={v} value={v}>{t('settings.'+v)}</option>)}</select></label><label>{t('settings.mode')}<select value={settings.mode} onChange={e=>change('mode',e.target.value)}>{['simple','advanced','expert'].map(v=><option key={v} value={v}>{t('settings.'+v)}</option>)}</select></label><p className="privacy-note">{t('landing.privacy')}</p><p className="hint">{t('settings.installHelp')}</p></div>}
 {section==='provider'&&<ProviderForm/>}{section==='visual'&&<VisualPanel/>}
 {section==='data'&&<div className="settings-fields"><p>{t('settings.saveNote')}</p><button className="button primary" disabled={!state.activeChatId||state.sending} onClick={()=>void run(async()=>download(await exportSave(state.activeChatId!,settings),'world.ocwsave'))}><Icon name="download"/>{t('settings.exportSave')}</button><label className="button secondary file-button"><Icon name="upload"/>{t('settings.importSave')}<input type="file" accept=".ocwsave,application/json" disabled={state.sending} onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{const result=await importSave(file);await updateSettings(result.settings);await selectChat(result.chatId);patchApp({notice:'imported'})});e.target.value=''}}/></label>
 <button className="button secondary" disabled={!state.activeChatId||state.sending} onClick={()=>void run(async()=>download(await exportChat(state.activeChatId!,'json'),'chat.json'))}>{t('chat.exportJson')}</button><button className="button secondary" disabled={!state.activeChatId||state.sending} onClick={()=>void run(async()=>download(await exportChat(state.activeChatId!,'md'),'chat.md'))}>{t('chat.exportMd')}</button><hr/><button className="text-button" onClick={()=>void run(async()=>patchApp({notice:await requestPersistence()?'persisted':'notPersisted'}))}>{t('settings.persist')}</button><p className="hint">{t('settings.persistNote')}</p></div>}
 </>;
}
export function VisualPanel(){const {t}=useTranslation(),state=useApp(),settings=state.settings,[expression,setExpression]=useState<Expression>('normal');const change=(key:keyof Settings,value:unknown)=>void run(()=>updateSettings({...settings,[key]:value}));return <div className="settings-fields"><label>{t('visual.particles')}<select value={settings.particles} onChange={e=>void run(async()=>{const value=e.target.value as Particle;await updateSettings({...settings,particles:value});await atmosphere(value)})}>{['none','rain','snow','fog','dust','firefly','leaves','light'].map(v=><option key={v} value={v}>{t('visual.'+v)}</option>)}</select></label><label>{t('visual.quality')}<select value={settings.performance} onChange={e=>change('performance',e.target.value)}>{['low','medium','high'].map(v=><option key={v} value={v}>{t('visual.'+v)}</option>)}</select></label>{(['motion','parallax','dynamicBackground'] as const).map(key=><label key={key} className="check-label"><input type="checkbox" checked={settings[key]} onChange={e=>change(key,e.target.checked)}/>{t('visual.'+(key==='dynamicBackground'?'dynamic':key))}</label>)}
 {state.world&&<><label className="button secondary file-button"><Icon name="upload"/>{t('visual.background')}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif,video/webm,video/mp4" onChange={e=>{const file=e.target.files?.[0];if(file)void run(()=>setBackground(file));e.target.value=''}}/></label><p className="hint">{t('visual.formats')}</p><label>{t('visual.expression')}<select value={expression} onChange={e=>{setExpression(e.target.value as Expression);patchApp({expression:e.target.value as Expression})}}>{['normal','happy','angry','sad','surprised','shy','fear','injured'].map(v=><option key={v} value={v}>{t('visual.'+v)}</option>)}</select></label><label className="button secondary file-button"><Icon name="upload"/>{t('visual.uploadExpression')}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const file=e.target.files?.[0];if(file)void run(()=>setExpressionAsset(file,expression));e.target.value=''}}/></label></>}
 </div>}
export function PersonaPanel(){const {t}=useTranslation(),state=useApp(),chat=state.chats.find(c=>c.id===state.activeChatId),persona=state.personas.find(p=>p.id===chat?.personaId),[name,setName]=useState(persona?.name??''),[description,setDescription]=useState(persona?.description??'');return <form onSubmit={e=>{e.preventDefault();void run(async()=>{await savePersona(name,description);patchApp({notice:'saved'})})}}><p className="hint">{t('persona.hint')}</p><label>{t('common.name')}<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>{t('common.description')}<textarea rows={6} value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="button primary">{t('common.save')}</button></form>}
export function LorePanel(){const {t}=useTranslation(),state=useApp(),[selected,setSelected]=useState<string>(),[content,setContent]=useState(''),[keys,setKeys]=useState('');return <><label className="button secondary file-button"><Icon name="upload"/>{t('lore.import')}<input type="file" accept=".json" onChange={e=>{const file=e.target.files?.[0];if(file&&state.selectedCharacterId)void run(async()=>{await importWorldbook(file,state.selectedCharacterId!);await refresh()});e.target.value=''}}/></label>{state.books.length?state.books.map(book=><section className="lore-book" key={book.id}><h3>{book.name}</h3>{book.entries.map(entry=><article className="lore-entry" key={entry.id}><label className="check-label"><input type="checkbox" checked={entry.enabled} onChange={e=>void run(async()=>{await books.update(book.id,{entries:book.entries.map(x=>x.id===entry.id?{...x,enabled:e.target.checked}:x)});await refresh()})}/><strong>{entry.keys.join(', ')||t('lore.constant')}</strong></label><p>{entry.content}</p><button className="text-button" onClick={()=>{setSelected(book.id+':'+entry.id);setContent(entry.content);setKeys(entry.keys.join(', '))}}>{t('common.edit')}</button>{selected===book.id+':'+entry.id&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{await books.update(book.id,{entries:book.entries.map(x=>x.id===entry.id?{...x,content,keys:keys.split(/[,，]/).map(k=>k.trim()).filter(Boolean)}:x)});setSelected(undefined);await refresh()})}}><label>{t('lore.keys')}<input value={keys} onChange={e=>setKeys(e.target.value)}/></label><label>{t('lore.content')}<textarea rows={5} value={content} onChange={e=>setContent(e.target.value)}/></label><button className="button primary">{t('common.save')}</button></form>}</article>)}</section>):<Empty text={t('lore.empty')}/>}</>}
export function ContextPanel(){const {t}=useTranslation(),state=useApp(),ctx=state.context;return <>{ctx?<><p className="tag">{t('context.tokens',{count:ctx.estimatedTokens})}</p><p className="hint">{t('context.trimmed',{count:ctx.trimmedMessages})}</p><details><summary>{t('lore.activation')}</summary>{ctx.lore.map((r,i)=><p key={i}>{r.book} · {r.id} — {t('lore.reason.'+r.reason)}</p>)}</details>{ctx.sections.map((s,i)=><details key={i}><summary>{t('context.'+(s.name.startsWith('lore:')?'lore':s.name))} <small>{s.tokens}</small></summary><pre>{s.content}</pre></details>)}<details><summary>{t('context.raw')}</summary><pre>{JSON.stringify(ctx.messages,null,2)}</pre></details></>:<Empty text={t('context.empty')}/>}<details><summary>{t('context.transactions')}</summary><pre>{JSON.stringify(state.transactions.map(({before,...tx})=>tx),null,2)}</pre></details></>}
export function CharacterPanel(){const {t}=useTranslation(),state=useApp(),character=state.characters.find(c=>c.id===state.selectedCharacterId);if(!character)return null;return <>{character.compatibilityWarnings?.map(w=><p className="callout" key={w}>{t('compat.'+w)}</p>)}<button className="button secondary" onClick={()=>void run(()=>exportOriginal(character))}><Icon name="download"/>{t('character.original')}</button>{(['description','personality','scenario','examples'] as const).map(key=><section className="character-copy" key={key}><h3>{t('character.'+key)}</h3><p>{character[key]||'—'}</p></section>)}</>}
export function HelpPanel(){const {t}=useTranslation();return <div className="help">{['getting','world','lore','data','errors','advanced'].map(id=><details key={id} open={id==='getting'}><summary>{t('help.'+id)}</summary><p>{t('help.'+id+'Body')}</p></details>)}</div>}
