import {GuideHint} from './UserGuide.tsx';
import {usesProviderSamplingDefaults} from '../providers/adapter.ts';
import {providerPresets,normalizeProvider} from '../providers/presets.ts';
import {useEffect,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {defaultProvider,type ProviderConfig} from '../domain/types.ts';
import {configureProvider,testProvider,modelList} from '../app/service.ts';
import {useApp,run,reportError,patchApp} from '../app/store.ts';
import {Icon} from './primitives.tsx';
export function ProviderForm({onSaved}:{onSaved?:()=>void}){
 const {t}=useTranslation(),current=useApp(s=>s.provider),mode=useApp(s=>s.settings.mode);const [config,setConfig]=useState(()=>normalizeProvider(current)),[models,setModels]=useState<{id:string;name:string}[]>([]),[testing,setTesting]=useState(false),[connected,setConnected]=useState(false),[headers,setHeaders]=useState(JSON.stringify(current.headers,null,2)),[modelLoading,setModelLoading]=useState(false);
 const set=(changes:Partial<ProviderConfig>)=>{setConfig(c=>({...c,...changes}));setConnected(false)};
 const choose=(kind:ProviderConfig['kind'])=>{setConfig({...defaultProvider,kind,baseUrl:providerPresets.find(p=>p.kind===kind)?.baseUrl??'',protocol:kind==='claude'?'anthropic':'openai',model:kind==='mock'?'demo-primary':'',apiKey:''});setHeaders('{}');setModels([]);setConnected(false)};
 const loadModels=async()=>{if(modelLoading||config.kind==='mock')return;setModelLoading(true);try{setModels(await modelList(validated()))}catch{patchApp({notice:undefined});reportError(new Error('models'))}finally{setModelLoading(false)}};
 const nativeClaude=config.kind==='claude'||config.protocol==='anthropic',sampling=!nativeClaude&&!usesProviderSamplingDefaults(config);
 const validated=()=>{let parsed;try{parsed=JSON.parse(headers);if(!parsed||Array.isArray(parsed)||typeof parsed!=='object'||Object.values(parsed).some(v=>typeof v!=='string'))throw Error()}catch{throw new Error('headerJson')}return {...config,headers:parsed as Record<string,string>,contextLimit:Math.max(2048,Math.min(1000000,config.contextLimit)),maxTokens:Math.max(32,Math.min(16384,config.maxTokens))}};
 return <form className="provider-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await configureProvider(validated());onSaved?.();if(!onSaved)patchApp({notice:'saved'})})}}>
  <GuideHint topic="connection"/><label>{t('provider.kind')}<select value={config.kind} onChange={e=>choose(e.target.value as ProviderConfig['kind'])}>{providerPresets.map(p=><option key={p.kind} value={p.kind}>{p.kind==='mock'?t('provider.demo'):p.kind==='custom'?t('provider.custom'):p.name}</option>)}</select></label>
  {config.kind!=='mock'?<><label>{t('provider.key')}<input type="password" autoComplete="off" spellCheck={false} value={config.apiKey} onChange={e=>set({apiKey:e.target.value})} onBlur={()=>{if(config.apiKey&&config.baseUrl)void loadModels()}} placeholder="••••••••••••••••"/></label><p className="hint"><Icon name="lock"/>{t('provider.private')}</p>
  <label>{t('provider.model')}<input required list="provider-models" value={config.model} onChange={e=>set({model:e.target.value})} placeholder={t('provider.manual')}/><datalist id="provider-models">{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</datalist></label>
  <button type="button" className="text-button" disabled={modelLoading||!config.baseUrl} onClick={()=>void loadModels()}>{modelLoading?t('provider.testing'):t('provider.models')}</button>
  {true&&<label>{t('provider.endpoint')}<input required type="url" value={config.baseUrl} onChange={e=>set({baseUrl:e.target.value})} placeholder="https://…/v1"/></label>}
  {config.kind==='custom'&&<label>{t('provider.protocol')}<select value={config.protocol??'openai'} onChange={e=>set({protocol:e.target.value as 'openai'|'anthropic'})}><option value="openai">OpenAI Chat Completions</option><option value="anthropic">Anthropic Messages</option></select></label>}{config.kind==='qwen'&&<p className="hint">{t('provider.qwenRegion')}</p>}{(config.kind==='claude'||config.protocol==='anthropic')&&<p className="hint">{t('provider.claudeBrowser')}</p>}<details><summary>{t('provider.more')}</summary><div className="form-grid">{sampling&&<><label>{t('provider.temperature')}<input type="number" min="0" max="2" step="0.1" value={config.temperature} onChange={e=>set({temperature:Number(e.target.value)})}/></label><label>{t('provider.topP')}<input type="number" min="0.01" max="1" step="0.01" value={config.topP} onChange={e=>set({topP:Number(e.target.value)})}/></label></>}<label>{t('provider.context')}<input type="number" min="2048" max="1000000" value={config.contextLimit} onChange={e=>set({contextLimit:Number(e.target.value)})}/></label><label>{t('provider.maxTokens')}<input type="number" min="32" max="16384" value={config.maxTokens} onChange={e=>set({maxTokens:Number(e.target.value)})}/></label></div><label className="check-label"><input type="checkbox" checked={config.streaming} onChange={e=>set({streaming:e.target.checked})}/>{t('provider.streaming')}</label>{!nativeClaude&&<label className="check-label"><input type="checkbox" checked={config.structuredOutput} onChange={e=>set({structuredOutput:e.target.checked})}/>{t('provider.structured')}</label>}{!sampling&&<p className="hint">{t('provider.samplingDefault')}</p>}<label>{t('provider.headers')}<textarea spellCheck={false} value={headers} onChange={e=>setHeaders(e.target.value)} rows={3}/></label></details></>:<p className="callout">{t('wizard.demo')}</p>}
  <div className="form-actions"><button type="button" className={`button secondary ${connected?'success':''}`} disabled={testing||(config.kind!=='mock'&&!config.model)} onClick={()=>void run(async()=>{setTesting(true);try{await testProvider(validated());setConnected(true)}finally{setTesting(false)}})}><Icon name={connected?'check':'spark'}/>{testing?t('provider.testing'):connected?t('provider.connected'):t('provider.test')}</button><button className="button primary" disabled={testing} type="submit">{onSaved?t('common.continue'):t('common.save')}<Icon name="arrow"/></button></div>
 </form>;
}
