import {useState} from 'react';
import {useTranslation} from 'react-i18next';
type Pair=[string,string];
type Lesson={id:string;title:Pair;steps:Pair[]};
const lessons:Lesson[]=[
 {id:'start',title:['第一次玩：从零开始','First story: start here'],steps:[
 ['首页选择「先遇见艾琳」，或导入你自己的 PNG / JSON 角色卡。想先熟悉操作，可在模型服务选择离线演示；它不是能自由思考的真实 AI。','Choose the example character on the home page, or import a PNG / JSON character card. Select Offline demo as the provider to explore without a real AI connection; its replies are scripted.'],
 ['按引导选择角色、连接模型、进入世界。第一次只需发一句「你好，你是谁？」；真实服务发送消息可能收费。','Follow the character, model and enter-world steps. Start with “Hello, who are you?” Sending to a real provider may cost money.'],
 ['看到回复后，可查看 WORLD 中的事实和经历。聊天是角色说的话，世界面板记录的是已提交的变化，两者不必每句话都同步。','After a reply, inspect facts and events in WORLD. Chat contains what characters say; WORLD records committed changes, not every sentence.'],
 ['设置 → 数据 → 导出存档，找到下载的文件。这是第一次完整备份。要玩高级功能时，再将设置中的界面复杂度切到高级或专家。','Open Settings → Data → Export save, then locate the downloaded file. This is your first full backup. Switch interface complexity to Advanced or Expert only when you need more controls.']]},
 {id:'connection',title:['连接模型：每个格子填什么','Model connection: what each field means'],steps:[
 ['模型服务（Provider）是提供 AI 的公司或平台；API Key 是访问凭据；Model ID 是平台要求的准确模型名，不一定是宣传名称。三者必须配套。','Provider is the AI service; API Key is its access credential; Model ID is the exact model identifier accepted by that service, which may differ from its marketing name. They must match.'],
 ['Base URL 是接口基础地址，不是官网登录页。使用服务商提供的地址；自定义兼容接口通常填到 /v1，不要自行追加 /chat/completions。自定义协议选择服务商支持的 OpenAI 或 Anthropic 格式。','Base URL is the API base, not the sign-in website. Use your provider’s documented base, often ending in /v1 for compatible APIs; do not append /chat/completions yourself. Choose the supported OpenAI or Anthropic protocol for custom connections.'],
 ['可以手填模型名。读取模型列表会联网；填写密钥后移开焦点也可能自动读取列表。「测试连接」会请求服务，可能计费；保存配置与测试连接是不同操作。','You can type the model ID manually. Loading the model list uses the network; leaving the key field may also load it automatically. Test connection sends a request and may incur charges. Saving and testing are separate actions.'],
 ['Token 是模型处理文字的单位，不等于字数。上下文上限是本轮输入与回复的预算，最大回复长度只限制输出。先保留默认采样设置；温度和 Top P 影响表达变化，不能修复错误的地址或密钥。','Tokens are model text units, not words or characters. Context limit budgets input and output; maximum reply length limits output. Keep sampling defaults initially. Temperature and Top P affect variation, not invalid credentials or endpoints.'],
 ['流式回复表示边生成边显示。连接成功后仍需保存。不要把密钥写进角色 Prompt、世界书、截图或分享的预设里。','Streaming displays text as it arrives. Save after a successful test. Do not put keys in character prompts, worldbooks, screenshots or shared presets.']]},
 {id:'creation',title:['自己做卡：角色、Prompt 与世界观','Create a card: character, prompt and world'],steps:[
 ['顶部「创建角色 / 世界」进入创作室。先填写名字、角色描述、性格和开场白，再补场景、世界观与示例对话，最后保存。','Open Create character / world at the top. Start with name, description, personality and greeting, then add scenario, worldview and example dialogue, and save.'],
 ['Prompt 是给模型的写作指令。例如「用第一人称回应，每次一到三段，不替玩家做决定」。世界观是故事背景，例如「这座城靠潮汐驱动机械」。不要将 API 密钥放进去。','A prompt gives writing instructions, such as “Reply in first person in one to three paragraphs; do not decide the player’s actions.” Worldview describes the setting, such as a city powered by tides. Neither field needs an API key.'],
 ['场景说明当前从哪里开始；开场白是玩家最先读到的话；示例对话帮助表达口吻。Persona 则是玩家身份，不是角色身份。修改角色设定不会自动把描述变成已发生的世界事实。','Scenario establishes the starting situation; greeting is the first text players see; examples demonstrate voice. Persona describes the player, not the character. Changing a description does not automatically commit world facts.']]},
 {id:'lore',title:['世界书：按需要补充设定','Worldbook: bring in relevant lore'],steps:[
 ['世界书是一组按条件加入本轮上下文的设定。例：主关键词填「灯塔」，正文写「灯塔位于北岸，每逢浓雾敲钟」。保存并在聊天中提到灯塔，才可能触发。','A worldbook contains lore entries included when their conditions match. Example: key “lighthouse”, content “The lighthouse stands on the north shore and rings its bell in fog.” Save and mention the lighthouse in chat to make it eligible.'],
 ['高级触发中的扫描消息数决定往前看多少条消息；预算限制世界书占用的估算 tokens。预算不够时，条目可能被省略，触发不等于保证进入最终请求。','Scan depth sets how many recent messages are examined. The token budget caps estimated lore usage. An eligible entry may still be omitted if the worldbook or overall context budget is exhausted.'],
 ['辅助关键词是在主关键词之外增加条件。例如辅助词「夜晚」，勾选辅助条件后，任一/全部表示至少一个/全部辅助词匹配；全部不匹配/不全匹配是反向条件。','Secondary keys add conditions beyond primary keys. Add “night” and enable secondary conditions. Any/All require one/all secondary matches; None/Not all invert those conditions.'],
 ['始终触发跳过主关键词匹配，但仍受启用状态、辅助条件、兼容性和预算限制。优先级越高越先分预算；整词匹配对连续中文可能比预期更严格，中文新手可先不勾选。','Always activate bypasses primary matching, but not enabled state, secondary conditions, compatibility or budgets. Higher priority gets budget first. Whole-word matching may be too strict for continuous Chinese text; leave it off initially.'],
 ['递归允许一条设定触发另一条，最多四轮。「不被递归触发」只允许原始聊天触发该条；「不触发其他条目」阻止它继续带出别的条目。保存后在专家模式的上下文检查中看实际内容与省略原因。','Recursion lets lore trigger more lore, up to four passes. Exclude from recursion limits an entry to the original scan; prevent recursion stops its text triggering others. Save and inspect the actual context in Expert mode for inclusion and omission reasons.']]},
 {id:'writing',title:['写作预设、作者注释与排序','Presets, author notes and ordering'],steps:[
 ['高级模式打开「对话写作设置」。写作提示词作用于当前故事，不修改原始卡。例：「少用旁白，多用角色动作表达情绪」。保存后才用于后续生成。','Open writing settings in Advanced mode. A writing prompt affects this story without editing the original card. Example: “Use actions to convey emotion and keep narration brief.” Save to apply it to subsequent generation.'],
 ['作者注释是反复提醒模型的短指令；频率控制隔多少次玩家发言加入，设为 0 不加入。系统位置放在系统提示中；历史位置按消息深度插入，0 靠近最新消息。','An author note is a short recurring instruction. Frequency controls the player-message interval; zero disables insertion. System position adds it to system instructions; history position inserts it at a message depth, with zero near the newest message.'],
 ['补充提示词排序只移动写作提示词、系统作者注释和插件提示词三组。不会任意移动角色事实或历史位置注释，也不保证后面的指令一定压过前面的指令。','Supplementary ordering moves the writing, system-note and plugin groups only. It does not freely rearrange world facts or history-position notes, and later instructions do not automatically override earlier ones.'],
 ['另存为预设可以复用；选择或导入预设后还需保存到本故事。预设不是故事备份，不包含全部聊天、世界状态或 API 配置。','Store a preset to reuse settings. Selecting or importing one still requires saving to the current story. Presets are not story backups and do not contain full chat, world state or API connections.']]},
 {id:'memory',title:['向量检索与独立嵌入连接','Vector retrieval and embedding connection'],steps:[
 ['向量检索会寻找意思接近的旧事件、对白或资料，不是无限记忆。嵌入模型把文本转换为用于比较的数字；聊天模型负责回复，两者可能来自不同平台。','Vector retrieval finds semantically related events, dialogue or references; it is not unlimited memory. An embedding model converts text into numbers for comparison, while a chat model writes replies. They may use different providers.'],
 ['专家模式 → 对话写作设置 → 高级扩展与检索。先决定共用聊天连接还是勾选独立嵌入连接。共用时填写聊天平台支持的嵌入模型，不要直接把聊天模型名称照搬进去。','Open writing settings → advanced extensions and retrieval in Expert mode. Choose the chat connection or a separate embedding connection. For a shared connection, enter a supported embedding model, not just the chat model’s name.'],
 ['独立连接填写 HTTPS 基础地址、嵌入模型、Key，点击「保存嵌入连接」；它由本机故事共用。再启用检索并保存写作设置。两个保存按钮负责不同内容，保存本身不测试服务。','For a separate connection, enter its HTTPS base, embedding model and key, then Save embedding connection. It is shared locally. Enable retrieval and save writing settings separately. These buttons save different things and do not test the service.'],
 ['可导入 TXT / Markdown 资料，单文件最多 64 KiB 且正文最多 16,000 字符，最多八份。资料供本故事成员共同参考，不要放仅某个角色能知道的秘密。','Import TXT / Markdown references, up to 64 KiB and 16,000 text characters each, with at most eight documents. References are shared among story members; do not use them for character-private secrets.'],
 ['启用后参考文本与当前输入会发到所选嵌入接口，可能收费；失败会提示并保留普通召回。清除索引不等于删除原资料，下次可能重新计费建立索引。导入存档后检索默认关闭，独立密钥不会跟着迁移。','Enabled retrieval sends reference text and the current input to the embedding endpoint and may cost money. Failure preserves normal recall. Clearing the index does not delete references and may cause re-indexing charges. Imported saves disable retrieval; separate credentials do not migrate.']]},
 {id:'extensions',title:['宏和插件：按需使用','Macros and plugins: optional tools'],steps:[
 ['宏是文本占位符或简单模板，例如 {{char}} 表示角色名、{{user}} 表示玩家名。高级宏需要显式启用；可先使用界面中的预览检查展开结果。','Macros are placeholders or templates: {{char}} means the character name and {{user}} the player name. Advanced macros require enabling; use the preview to inspect their output first.'],
 ['高级变量只在单次模板展开中有效，不是永久世界状态。条件、循环都有上限；不支持的酒馆语法不会自动变成可用功能。','Advanced variables live only during one template expansion, not as permanent world state. Conditions and loops are bounded; unsupported Tavern syntax is not automatically compatible.'],
 ['插件目前仅支持本项目格式的提示词补充插件。可下载界面的原创示例，检查代码与许可证后导入、启用并保存。不要直接导入 SillyTavern 扩展目录。','Plugins currently support this project’s prompt-supplement format only. Download the original example from the UI, inspect its code and license, then import, enable and save. Do not import SillyTavern extension directories.'],
 ['插件不会获得你的 API 密钥，也不能直接修改世界事实。导入存档或预设后的插件默认暂停；失败的插件会跳过并提示。','Plugins do not receive your API credentials or directly modify world facts. Imported presets/saves pause plugins by default; failing plugins are skipped with a notice.']]},
 {id:'world',title:['行动、群聊与回退','Actions, groups and rollback'],steps:[
 ['对话输入适合自由交流；快捷行动适合明确交给系统处理的赠送、寄存、拾取等操作。所有者、持有人、所在地点分别回答「是谁的」「谁拿着」「在哪里」。','Free chat is for conversation; quick actions make supported operations such as giving, storing and picking up explicit. Owner, holder and location mean whose item it is, who carries it and where it is.'],
 ['角色说「以后再说」不等于同意。查看 WORLD 的待定事项、事实与经历确认结果；不要仅凭角色措辞判断物品已经转移。','“Maybe later” is not acceptance. Check pending actions, facts and events in WORLD rather than inferring an item transfer from dialogue alone.'],
 ['群聊先选择成员和发言角色，再发送消息或执行一轮群聊。多人发言会增加模型请求与费用，不是一次调用免费生成所有角色。','Choose members and speaker for a group, then send or run a group round. Multiple speakers require more model requests and may increase costs.'],
 ['重生成会重新请求模型。编辑、删除历史消息或切换候选可能回退后续世界变化；大改剧情前先创建分支或导出存档。','Regeneration sends another model request. Editing/deleting history or switching candidates can roll back later world changes. Branch or export before major story changes.']]},
 {id:'media',title:['背景、音乐与阅读效果','Background, music and reading'],steps:[
 ['创作室中导入背景图片、视频和音乐，调整顺序、轮换间隔、遮罩与立绘大小后保存。媒体保存在本浏览器，文件越大越占存储。','Import backgrounds, video and music in the creator; adjust ordering, rotation interval, shade and portrait scale, then save. Media stays in this browser and large files consume storage.'],
 ['故事场景中的左右箭头手动换背景；固定地点背景可能优先于轮换列表。音乐需点击播放，可选择曲目和调音量；有文件不等于浏览器允许自动播放。','Scene arrows change backgrounds manually; a fixed location background can take precedence over rotation. Click Play for music, then select a track or volume. Having a file does not mean autoplay is allowed.'],
 ['静心阅读临时隐藏背景和立绘、停止轮换及粒子，但不暂停独立音乐；需要安静时再点音乐暂停。离开场景后此开关可能重置。','Quiet scene temporarily hides background and portrait and stops rotation and particles. Music is independent: pause it separately for silence. This toggle may reset when leaving the scene.'],
 ['设置 → 视觉可降低效果。低性能模式和系统减少动态偏好会限制动画；某些 GIF 不会自动冻结，可用静心阅读隐藏。加载失败或不支持的视频编码可尝试换文件。','Reduce effects in Settings → Visual. Low-performance mode and system reduced-motion preferences limit animation. Some GIFs do not freeze automatically; Quiet scene hides them. Try another file if media cannot load or its codec is unsupported.']]},
 {id:'backup',title:['存档、换设备与网站更新','Backups, devices and updates'],steps:[
 ['自动保存保存在当前浏览器、当前网址，不是云同步。换手机、浏览器或从本地网址切换到线上网址，不会自动带走存档。','Autosave belongs to this browser and site address; it is not cloud sync. Switching devices, browsers or from localhost to the public site does not transfer saves.'],
 ['设置 → 数据 → 导出存档，确认下载完成并能找到 .ocwsave 文件，再点「我已保存好备份文件」。确认日期是手动记录，不代表系统验证过文件；聊天 JSON/Markdown 导出不等于完整备份。','Settings → Data → Export save. Locate the downloaded .ocwsave file before confirming backup. The confirmation is a manual record, not file verification. Chat JSON/Markdown exports are not full backups.'],
 ['在新设备导入完整存档，会创建新的本地故事分支，不覆盖原故事。模型密钥需要重新配置；导出原始卡只带原卡，不包括后续故事。','Import a full save on the new device to create a new local story branch without overwriting the original. Reconfigure credentials. Export original card contains the original card, not subsequent gameplay.'],
 ['持久存储保护可减少浏览器自动回收，但不能防止手动清空网站数据。空间接近上限先备份，再整理媒体；不要为了排错直接清空本站数据。','Persistent storage reduces automatic reclamation but cannot prevent manual site-data deletion. Back up before removing media when space is low; do not clear all site data as a first troubleshooting step.'],
 ['出现新版按钮时先保存编辑，再更新。取消更新可继续当前页面；未保存输入不会自动恢复。更新通常保留本机故事，重要更新前仍建议导出备份。','Save edits before applying a detected update. Cancel to keep using the current page; unsaved text is not automatically recovered. Updates normally retain local stories, but export before important upgrades.']]},
 {id:'trouble',title:['遇到问题怎么查','Troubleshooting'],steps:[
 ['没有设置入口：先检查是否在简单模式，高级写作选项需要高级/专家模式。保存后不生效：确认保存的是本故事设置，而不只是另存了预设。','Missing controls: check interface complexity; advanced writing needs Advanced/Expert. Changes not applied: save to the current story, not just to the preset library.'],
 ['认证失败：核对 Key、地域和基础地址；模型不存在：核对准确 Model ID；额度不足或限流：检查服务账户，不要连续反复点击生成。','Authentication failure: check key, region and endpoint. Missing model: verify its exact ID. Quota/rate limits: check your service account rather than repeatedly generating.'],
 ['网络或跨域错误：浏览器必须获服务端允许才能直连，网页无法自行绕过。回复慢：等待或停止，不要把仍在生成误判成存档损坏。','Network/CORS errors: the server must allow browser access; this page cannot bypass it. Slow replies: wait or stop generation rather than assuming save corruption.'],
 ['世界书没出现：检查启用、关键词、扫描深度、辅助条件和预算；显示不支持的规则不会注入。独立检索失败：确认嵌入连接单独保存，接口支持 /embeddings，且填写的是嵌入模型。','Missing lore: check enabled state, keys, scan depth, secondary conditions and budgets. Unsupported entries are not injected. Retrieval failure: save the embedding connection separately and confirm /embeddings support and an embedding model.'],
 ['反馈问题时提供操作步骤、错误提示、设备与浏览器、是否能够复现。隐藏 Key 和私人对白；暂时无法复现也不必清除存档。','When reporting, include steps, error text, device/browser and reproducibility. Hide keys and private dialogue. Do not delete saves just because an issue cannot be reproduced.']]}
];
export function GuideHint({topic}:{topic:string}){const {i18n}=useTranslation(),index=i18n.language.startsWith('zh')?0:1,lesson=lessons.find(l=>l.id===topic);if(!lesson)return null;return <details className="guide-hint"><summary>{lesson.title[index]}</summary><ol>{lesson.steps.map((step,i)=><li key={i}>{step[index]}</li>)}</ol></details>}
export function UserGuide(){const {i18n}=useTranslation(),index=i18n.language.startsWith('zh')?0:1,[query,setQuery]=useState('');const filtered=lessons.filter(l=>[l.title[index],...l.steps.map(s=>s[index])].join(' ').toLowerCase().includes(query.trim().toLowerCase()));return <section className="user-guide"><h3>{index===0?'从入门到高级：操作教程':'Step-by-step user guide'}</h3><p>{index===0?'第一次使用先读前两节，其余按需要展开。这里只讲当前已实现的功能。':'Read the first two lessons to get started, then open topics as needed. This guide covers implemented features.'}</p><label>{index===0?'查找功能或术语':'Find a feature or term'}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={index===0?'例如：世界书、Token、备份':'e.g. worldbook, token, backup'}/></label>{filtered.map(l=><GuideHint key={l.id} topic={l.id}/>)}{!filtered.length&&<p role="status">{index===0?'没有找到，请尝试更短的关键词。':'No results. Try a shorter search term.'}</p>}</section>}
