import React from 'react';
import {createRoot} from 'react-dom/client';
import App from '../ui/App.tsx';
import {patchApp,useApp} from './store.ts';
import '../ui/style.css';
import {registerSW} from 'virtual:pwa-register';
const updateServiceWorker=registerSW({immediate:true,onNeedRefresh(){patchApp({updateReady:true})}});
window.addEventListener('oc-apply-update',()=>{if(!useApp.getState().sending)void updateServiceWorker(true)});
const Acceptance=React.lazy(()=>import('../ui/Acceptance.tsx'));
const LiveCheck=React.lazy(()=>import('../ui/LiveCheck.tsx'));
createRoot(document.getElementById('root')!).render(<React.StrictMode>{new URLSearchParams(location.search).has('acceptance')?<React.Suspense fallback="Loading…"><Acceptance/></React.Suspense>:new URLSearchParams(location.search).has('live-check')?<React.Suspense fallback="Loading…"><LiveCheck/></React.Suspense>:<App/>}</React.StrictMode>);
