import {z} from 'zod';
const id=z.string().min(1).max(200).refine(s=>!['__proto__','constructor','prototype'].includes(s));
const text=z.string().max(2_000_000),short=z.string().max(500),ids=z.array(id).max(10000);
export const entitySchema=z.object({id,type:z.enum(['person','item','place','information']),name:short,description:text,owner:id.optional(),holder:id.nullable().optional(),location:id.optional(),alive:z.boolean().optional(),knownBy:ids.optional(),usable:z.boolean().optional(),consumed:z.boolean().optional(),locked:z.boolean().optional(),keyId:id.optional(),backgroundId:id.optional()});
const particles=z.enum(['none','rain','snow','fog','dust','firefly','leaves','light']);
export const worldSchema=z.object({id,revision:z.number().int().nonnegative(),day:z.number().int().positive(),minutes:z.number().int().min(0).max(1439),weather:particles,location:id,participants:ids,entities:z.record(id,entitySchema),promises:z.record(id,z.object({text,actor:id,target:id,status:z.enum(['made','accepted','broken'])})),relationships:z.record(id,short)});
const expression=z.enum(['normal','happy','angry','sad','surprised','shy','fear','injured']);
const designSchema=z.object({backgroundIds:ids,musicIds:ids,rotate:z.boolean(),rotationSeconds:z.number().min(5).max(600),musicVolume:z.number().min(0).max(1),overlayOpacity:z.number().min(0).max(0.85),portraitScale:z.number().min(0.6).max(1.5),particles});
const characterSchema=z.object({id,name:short,description:text,personality:text,scenario:text,examples:text,systemPrompt:text,postHistory:text,greetings:z.array(text).max(100),creator:short,tags:z.array(short).max(1000),originalAssetId:id,portraitId:id.optional(),expressions:z.partialRecord(expression,id),worldbookIds:ids,createdAt:z.number(),sourceSpec:short,builtin:z.boolean().optional(),worldview:text.optional(),compatibilityWarnings:z.array(short).optional(),design:designSchema.optional()});
const messageSchema=z.object({id,chatId:id,role:z.enum(['user','assistant']),content:text,variants:z.array(text).max(1000),selected:z.number().int().nonnegative(),createdAt:z.number(),status:z.enum(['complete','interrupted']),expression:expression.optional(),speakerId:id.optional(),groupTurn:z.boolean().optional()}).refine(m=>m.selected<m.variants.length&&m.content===m.variants[m.selected]);
const kinds=z.enum(['STORE_ITEM','RETURN_ITEM','TRANSFER_ITEM','USE_ITEM','MOVE','TAKE_ITEM','DROP_ITEM','CHANGE_LOCATION','TIME_ADVANCE','MAKE_PROMISE','ACCEPT_PROMISE','BREAK_PROMISE','ACCEPT_INVITATION','REJECT_INVITATION','REVEAL_INFORMATION','LEARN_INFORMATION','ACCEPT_CLAIM','REJECT_CLAIM','RELATIONSHIP_MILESTONE']);
const candidateShape={id,worldId:id,sourceMessageId:id,expectedRevision:z.number().int().nonnegative(),kind:kinds,actor:id,target:id.optional(),entityId:short.optional(),destination:id.optional(),text:text.optional(),minutes:z.number().optional(),confidence:z.number().min(0).max(1),origin:z.enum(['structured','language']),requiresConsent:z.boolean()};
const transactionSchema=z.object({...candidateShape,status:z.enum(['pending','committed','rejected']),reason:short,decision:z.enum(['ACCEPT','REJECT','DEFER','UNCLEAR']).optional(),createdAt:z.number(),before:worldSchema.optional()});
const eventSchema=z.object({id,worldId:id,timestamp:z.number(),world_time:z.object({day:z.number(),minutes:z.number()}),participants:ids,event_type:kinds,summary:text,entities:ids,importance:z.number().min(0).max(1),source_message_id:id,transactionId:id,status:z.enum(['committed','reverted']),details:z.object({actor:short,target:short.optional(),entity:short.optional(),destination:short.optional(),text:text.optional()})});
export const settingsSchema=z.object({language:z.enum(['zh-CN','en-US']),theme:z.enum(['dark','light','system']),mode:z.enum(['simple','advanced','expert']),performance:z.enum(['low','medium','high']),particles,motion:z.boolean(),parallax:z.boolean(),dynamicBackground:z.boolean(),tutorialDismissed:z.array(short).max(50)});
const assetSchema=z.object({id,characterId:id.optional(),kind:z.enum(['original','portrait','expression','background','audio']),name:short,mime:short,sha256:z.string().regex(/^[a-f0-9]{64}$/),expression:expression.optional(),base64:z.string().max(90_000_000)});
const bookSchema=z.object({id,characterId:id.optional(),name:short,raw:text,scanDepth:z.number().int().min(1).max(100),tokenBudget:z.number().int().min(128).max(8192),recursive:z.boolean().optional(),entries:z.array(z.object({id,keys:z.array(short),secondaryKeys:z.array(short),content:text,enabled:z.boolean(),constant:z.boolean(),selective:z.boolean(),caseSensitive:z.boolean(),priority:z.number(),position:z.enum(['before_char','after_char']),secondaryLogic:z.enum(['any','all','notAny','notAll']).optional(),wholeWords:z.boolean().optional(),excludeRecursion:z.boolean().optional(),preventRecursion:z.boolean().optional(),unsupported:z.boolean().optional()})).max(10000)});
export const saveSchema=z.object({format:z.literal('ocwsave'),version:z.literal(1),createdAt:z.number(),character:characterSchema,additionalCharacters:z.array(characterSchema).max(50).optional(),chat:z.object({id,characterId:id,name:short,createdAt:z.number(),updatedAt:z.number(),personaId:id.optional(),parentId:id.optional(),memberIds:ids.optional(),speakerId:id.optional(),mutedIds:ids.optional()}),messages:z.array(messageSchema).max(50000),world:worldSchema,events:z.array(eventSchema).max(50000),transactions:z.array(transactionSchema).max(50000),worldbooks:z.array(bookSchema).max(100),assets:z.array(assetSchema).max(200),persona:z.object({id,name:short,description:text}).optional(),settings:settingsSchema}).strict();
export function validateSave(input:unknown){
 const save=saveSchema.parse(input);const roster=[save.character,...(save.additionalCharacters??[])],characterIds=new Set(roster.map(c=>c.id));const unique=(rows:{id:string}[])=>new Set(rows.map(r=>r.id)).size===rows.length;
 if(![save.messages,save.events,save.transactions,save.assets,save.worldbooks,[...roster,save.chat,...save.messages,...save.events,...save.transactions,...save.assets,...save.worldbooks,...(save.persona?[save.persona]:[])]].every(unique))throw new Error('invalidSave');
 const assetIds=new Set(save.assets.map(a=>a.id)),bookIds=new Set(save.worldbooks.map(b=>b.id)),messageIds=new Set(save.messages.map(m=>m.id)),txIds=new Set(save.transactions.map(t=>t.id));
 if(save.chat.characterId!==save.character.id||save.world.id!==save.chat.id||!assetIds.has(save.character.originalAssetId)||save.character.worldbookIds.some(id=>!bookIds.has(id))||save.messages.some(m=>m.chatId!==save.chat.id)||save.events.some(e=>e.worldId!==save.chat.id||!messageIds.has(e.source_message_id)||!txIds.has(e.transactionId))||save.transactions.some(t=>t.worldId!==save.chat.id||!messageIds.has(t.sourceMessageId)))throw new Error('invalidSave');
 for(const character of roster){
 if(character.design&&([...character.design.backgroundIds,...character.design.musicIds].some(id=>!assetIds.has(id))||character.design.musicIds.some(id=>save.assets.find(a=>a.id===id)?.kind!=='audio')))throw new Error('invalidSave');
 if(character.portraitId&&!assetIds.has(character.portraitId)||Object.values(character.expressions).some(id=>!assetIds.has(id)))throw new Error('invalidSave');
 if(save.assets.find(a=>a.id===character.originalAssetId)?.kind!=='original'||!assetIds.has(character.originalAssetId)||character.worldbookIds.some(id=>!bookIds.has(id)))throw new Error('invalidSave');}
 if(save.chat.memberIds?.some(id=>!characterIds.has(id))||save.chat.speakerId&&!(save.chat.memberIds??[save.character.id]).includes(save.chat.speakerId)||save.chat.mutedIds?.some(id=>!(save.chat.memberIds??[save.character.id]).includes(id))||save.messages.some(m=>m.speakerId&&!characterIds.has(m.speakerId)))throw new Error('invalidSave');
 if(save.assets.find(a=>a.id===save.character.originalAssetId)?.kind!=='original'||save.assets.some(a=>a.characterId&&!characterIds.has(a.characterId))||save.worldbooks.some(b=>b.characterId&&!characterIds.has(b.characterId))||save.chat.personaId!==save.persona?.id)throw new Error('invalidSave');
 for(const event of save.events){const tx=save.transactions.find(t=>t.id===event.transactionId);if(tx?.status!=='committed'||tx.sourceMessageId!==event.source_message_id||tx.kind!==event.event_type||event.participants.some(id=>save.world.entities[id]?.type!=='person'))throw new Error('invalidSave')}
 for(const tx of save.transactions)if(tx.status==='committed'&&(!tx.before||tx.before.revision!==tx.expectedRevision))throw new Error('invalidSave');
 for(const world of [save.world,...save.transactions.flatMap(t=>t.before?[t.before]:[])]){
  const es=world.entities;if(world.id!==save.chat.id||es[world.location]?.type!=='place'||!es.player||!es[save.character.id]||world.participants.some(id=>es[id]?.type!=='person'))throw new Error('invalidSave');
  for(const [key,e] of Object.entries(es))if(key!==e.id||(e.owner&&es[e.owner]?.type!=='person')||(e.holder&&es[e.holder]?.type!=='person')||(e.location&&!es[e.location])||(e.backgroundId&&!assetIds.has(e.backgroundId))||(e.knownBy?.some(id=>es[id]?.type!=='person'))||(e.keyId&&es[e.keyId]?.type!=='item'))throw new Error('invalidSave');
  if(Object.values(world.promises).some(p=>es[p.actor]?.type!=='person'||es[p.target]?.type!=='person')||Object.keys(world.relationships).some(id=>es[id]?.type!=='person'))throw new Error('invalidSave');
 }
 return save;
}
