import test from 'node:test';import assert from 'node:assert/strict';
import {renderProgram} from '../../src/context/program.ts';
import {cosine,parseVectors,visibleMemory} from '../../src/context/vectors.ts';
import {pluginSchema,writingSchema,importedWriting} from '../../src/domain/writing.ts';
test('nested conditions, loops and variables evaluate without persisting state',()=>{const vars={mood:'calm'};const text='{{setvar::n::1}}{{#if::mood::calm}}{{#repeat::3}}{{index}}:{{getvar::n}};{{addvar::n::2}}{{/repeat}}{{else}}wrong{{/if}}';assert.equal(renderProgram(text,vars),'1:1;2:3;3:5;');assert.deepEqual(vars,{mood:'calm'});assert.equal(renderProgram('{{#if::missing}}wrong{{else}}ok{{/if}}'),'ok');assert.equal(renderProgram('{{getvar::x}}',{x:'{{setvar::n::injected}}'}),'{{setvar::n::injected}}')});
test('program limits and malformed blocks fail without evaluating unknown commands',()=>{assert.equal(renderProgram('{{unknown::x}}'),'{{unknown::x}}');for(const text of ['{{#repeat::21}}x{{/repeat}}','{{#if::a}}x','{{else}}','{{#repeat::20}}'+ 'x'.repeat(4000)+'{{/repeat}}','{{#repeat::2}}'.repeat(9)+'x'+'{{/repeat}}'.repeat(9)])assert.throws(()=>renderProgram(text),/macro/);assert.equal(renderProgram('{{#if::a}}{{addvar::n::bad}}{{else}}fine{{/if}}'),'fine')});
test('vector validation rejects malformed dimensions, indices and values',()=>{assert.equal(cosine([1,0],[1,0]),1);assert.equal(cosine([1,0],[0,1]),0);assert.deepEqual(parseVectors({data:[{index:1,embedding:[0,1]},{index:0,embedding:[1,0]}]},2),[[1,0],[0,1]]);for(const data of [{data:[{index:0,embedding:[NaN]}]},{data:[{index:1,embedding:[1]}]},{data:[{index:0,embedding:[]}]},{data:[{index:0,embedding:['1']}]}])assert.throws(()=>parseVectors(data,1));assert.throws(()=>cosine([1],[1,2]))});
test('retrieval candidates exclude reverted and other-character events before embedding',()=>{const event=(id,status,participants)=>({id,status,participants,timestamp:1});assert.deepEqual(visibleMemory([event('yes','committed',['a']),event('private','committed',['b']),event('reverted','reverted',['a'])],'a').map(e=>e.id),['yes'])});
test('plugin manifests require license records; imported automation remains disabled',()=>{const plugin={format:'ocw-plugin',version:1,id:'test',name:'Test',license:'MIT',licenseText:'Test notice',source:'Original test fixture',code:'return "hello";',enabled:true};assert.equal(pluginSchema.parse(plugin).enabled,true);assert.throws(()=>pluginSchema.parse({...plugin,license:'AGPL-3.0'}));assert.throws(()=>pluginSchema.parse({...plugin,source:''}));assert.throws(()=>pluginSchema.parse({...plugin,permissions:['network']}));const writing=writingSchema.parse({plugins:[plugin],vectorsEnabled:true});const imported=importedWriting(writing);assert.equal(imported.plugins[0].enabled,false);assert.equal(imported.vectorsEnabled,false);assert.equal(writing.plugins[0].enabled,true)});
