import test from 'node:test';import assert from 'node:assert/strict';
import {buildContext} from '../../src/context/builder.ts';
import {initialWorld,makeCandidate,resolveTransaction} from '../../src/runtime/engine.ts';
import {interactionMemory} from '../../src/context/interactions.ts';
const char={id:'eileen',name:'Eileen',builtin:true,description:'Archivist',personality:'',scenario:'Archive',examples:'',systemPrompt:'',postHistory:'',worldbookIds:[],greetings:[],expressions:{},tags:[],creator:'fixture',originalAssetId:'original',sourceSpec:'v2',createdAt:0};
const msg=(id,content)=>({id,chatId:'test',role:'user',content,variants:[content],selected:0,status:'complete',createdAt:0});
function fixture(decision='REJECT',kind='TRANSFER_ITEM'){const w=initialWorld('test',char);const c=makeCandidate(w,kind,'offer',{requiresConsent:true,entityId:'ring',target:char.id,text:'I offer the ring.'});const r=resolveTransaction(w,c,decision,1);return {w,r,h:[msg('offer','I offer the ring.'),...Array.from({length:150},(_,i)=>msg('f'+i,'Weather '.repeat(40))),msg('last','Recall the ring offer.')]};}
test('refused and deferred interactions survive history trimming without changing facts',()=>{for(const decision of ['REJECT','DEFER']){const {w,r,h}=fixture(decision);const ctx=buildContext(char,h,w,[],[],undefined,8000,1024,undefined,undefined,[],{interactions:[r.transaction]});assert.ok(ctx.trimmedMessages>0);const memory=ctx.sections.find(s=>s.name==='interactions').content;assert.ok(memory.includes(decision==='REJECT'?'declined':'deferred'));assert.ok(memory.includes('NOT completed actions'));assert.equal(w.entities.ring.owner,'player');assert.deepEqual(r.world,w);}});
test('other worlds, characters, deleted causes, unresolved requests and committed actions are excluded',()=>{const {w,r,h}=fixture();const t=r.transaction;for(const bad of [{...t,worldId:'other'},{...t,target:'other'},{...t,sourceMessageId:'removed'},{...t,reason:'awaitingActor'},{...t,status:'committed'}])assert.equal(interactionMemory(char,h,w,[bad],900),'');assert.equal(interactionMemory({...char,id:'other'},h,w,[t],900),'');assert.equal(interactionMemory(char,h.filter(m=>m.id!=='offer'),w,[t],900),'');});
test('custody attempts remain distinct from gifts; no snapshots or secret entities are exposed',()=>{const {w,r,h}=fixture('DEFER','STORE_ITEM');const t={...r.transaction,before:{private:'SECRET'}};const text=interactionMemory(char,h,w,[t],900);assert.ok(text.includes('STORE_ITEM'));assert.ok(!text.includes('SECRET'));w.entities.hidden={id:'hidden',type:'information',name:'HIDDEN',knownBy:['player'],description:'SECRET'};assert.equal(interactionMemory(char,h,w,[{...t,entityId:'hidden'}],900),'');assert.equal(interactionMemory(char,h,w,[t],1),'');});
test('serialized transaction memory is reconstructed and removed when rollback deletes transactions',()=>{const {w,r,h}=fixture();const saved=JSON.parse(JSON.stringify({w,h,txs:[r.transaction]}));assert.equal(interactionMemory(char,saved.h,saved.w,saved.txs,900),interactionMemory(char,h,w,[r.transaction],900));saved.txs=[];assert.equal(interactionMemory(char,saved.h,saved.w,saved.txs,900),'');});

test('recall quotes the actual target response and distinguishes deferred from refused',()=>{for(const decision of ['REJECT','DEFER']){const {w,r,h}=fixture(decision);const reply={...msg('answer',decision==='REJECT'?'I refuse because the clasp is damaged.':'I need time to decide; ask me tomorrow.'),role:'assistant',speakerId:char.id};h.push(reply);const text=interactionMemory(char,h,w,[{...r.transaction,sourceMessageId:reply.id}],900);assert.ok(text.includes(reply.content));assert.ok(text.includes(decision==='REJECT'?'refused':'undecided'));assert.ok(text.includes('Do not invent motives'));}});
test('missing or differently attributed replies do not become invented response evidence',()=>{const {w,r,h}=fixture();let text=interactionMemory(char,h,w,[r.transaction],900);assert.ok(text.includes('unavailable'));assert.ok(!text.includes('responseExcerpt'));h.push({...msg('answer','PRIVATE OTHER RESPONSE'),role:'assistant',speakerId:'other'});text=interactionMemory(char,h,w,[{...r.transaction,sourceMessageId:'answer'}],900);assert.ok(!text.includes('PRIVATE OTHER RESPONSE'));assert.ok(text.includes('unavailable'));});
test('large response evidence is explicitly truncated within the memory budget',()=>{const {w,r,h}=fixture();h.push({...msg('answer','x'.repeat(5000)+' Maybe another day.'),role:'assistant',speakerId:char.id});const text=interactionMemory(char,h,w,[{...r.transaction,sourceMessageId:'answer'}],900);assert.ok(text.includes('"responseTruncated":true'));assert.ok(text.includes('Maybe another day.'));assert.ok(text.includes('[omitted]'));assert.ok(Math.ceil(text.length/2)<=900);});
