import test from 'node:test';import assert from 'node:assert/strict';
import {AnthropicProvider,createProvider,CompatibleProvider} from '../../src/providers/adapter.ts';
import {defaultProvider} from '../../src/domain/types.ts';import {providerPresets,normalizeProvider} from '../../src/providers/presets.ts';
const config={...defaultProvider,kind:'claude',protocol:'anthropic',apiKey:'fake-test-key',baseUrl:'https://api.anthropic.com/v1',model:'test-model'};
test('six requested API entries and an explicit offline demo are available',()=>{assert.deepEqual(providerPresets.map(p=>p.kind),['openai','claude','deepseek','glm','qwen','custom','mock']);assert.ok(createProvider(config) instanceof AnthropicProvider);assert.ok(createProvider({...config,kind:'custom',protocol:'anthropic'}) instanceof AnthropicProvider);assert.ok(createProvider({...config,kind:'deepseek',protocol:'openai'}) instanceof CompatibleProvider)});
test('legacy provider preserves its endpoint and credential as a custom connection',()=>{const old={...config,kind:'openrouter',baseUrl:'https://openrouter.ai/api/v1'};const updated=normalizeProvider(old);assert.equal(updated.kind,'custom');assert.equal(updated.baseUrl,old.baseUrl);assert.equal(updated.apiKey,old.apiKey)});
test('Claude uses native headers, top-level system and Messages body',()=>{const p=new AnthropicProvider(config),headers=p.authHeaders(),body=JSON.parse(p.body({messages:[{role:'system',content:'Rules'},{role:'user',content:'A'},{role:'user',content:'B'}]},true));assert.equal(headers.get('x-api-key'),'fake-test-key');assert.equal(headers.get('Authorization'),null);assert.equal(headers.get('anthropic-version'),'2023-06-01');assert.equal(body.system,'Rules');assert.equal(body.messages.length,1);assert.equal(body.messages[0].content,'A\n\nB');assert.ok(!('top_p' in body));assert.ok(!('temperature' in body))});
test('Claude streams only text deltas, preserves usage and requires message_stop',async()=>{const previous=globalThis.fetch;let request;globalThis.fetch=async(url,options)=>{request={url,options};const rows=[{type:'message_start',message:{usage:{input_tokens:12}}},{type:'content_block_delta',delta:{type:'thinking_delta',thinking:'not visible'}},{type:'content_block_delta',delta:{type:'text_delta',text:'你好'}},{type:'message_delta',usage:{output_tokens:3}},{type:'message_stop'}];return new Response(rows.map(r=>'data: '+JSON.stringify(r)+'\n\n').join(''))};try{const rows=[];for await(const row of new AnthropicProvider(config).streamChat({messages:[{role:'user',content:'Hi'}]}))rows.push(row);assert.equal(request.url,'https://api.anthropic.com/v1/messages');assert.equal(rows.at(-1).result.text,'你好');assert.equal(rows.at(-1).result.usage.total_tokens,15)}finally{globalThis.fetch=previous}});
test('OpenAI reasoning models use completion budget without unsupported sampling fields',()=>{const body=JSON.parse(new CompatibleProvider({...defaultProvider,model:'gpt-5'}).body({messages:[]},true));assert.ok(body.max_completion_tokens);assert.ok(!('max_tokens' in body));assert.ok(!('temperature' in body))});

test('Aliyun Kimi K3 omits fixed sampling for actor and resolver without changing model',()=>{
 const base={...defaultProvider,kind:'custom',model:'kimi-k3',baseUrl:'https://example.cn-beijing.maas.aliyuncs.com/compatible-mode/v1',temperature:0,topP:1};
 for(const purpose of ['actor','resolver']){const body=JSON.parse(new CompatibleProvider(base).body({purpose,messages:[]},false));assert.equal(body.model,'kimi-k3');assert.ok(!('temperature' in body));assert.ok(!('top_p' in body));}
 for(const config of [{...base,model:'glm-5.2'},{...base,baseUrl:'https://example.com/v1'},{...base,baseUrl:'https://maas.aliyuncs.com.example.org/v1'}]){const body=JSON.parse(new CompatibleProvider(config).body({messages:[]},false));assert.equal(body.top_p,1);assert.equal(body.temperature,0);}
});
