import test from 'node:test';
import assert from 'node:assert/strict';
import {resolverOptions,CompatibleProvider,readSSE,safeDetail,endpoint} from '../../src/providers/adapter.ts';
import {defaultProvider} from '../../src/domain/types.ts';
const config={...defaultProvider,apiKey:'test-secret-not-real',headers:{'X-Test':'private-header'},model:'mock'};
const stream=(text,size=1)=>{const bytes=new TextEncoder().encode(text);return new ReadableStream({start(c){for(let i=0;i<bytes.length;i+=size)c.enqueue(bytes.slice(i,i+size));c.close()}})};
test('SSE preserves UTF-8 across single-byte chunks, comments and CRLF',async()=>{const rows=[];for await(const row of readSSE(stream(': ping\r\ndata: 你好\r\ndata: 世界\r\n\r\ndata: [DONE]\r\n\r\n')))rows.push(row);assert.deepEqual(rows,['你好\n世界','[DONE]'])});
test('streaming accumulates content and usage with explicit finish',async()=>{const old=globalThis.fetch;let options;globalThis.fetch=async(url,init)=>{options=init;return new Response(stream('data: {"choices":[{"delta":{"content":"你好"}}]}\n\ndata: {"choices":[{"delta":{},"finish_reason":"stop"}],"usage":{"total_tokens":3}}\n\ndata: [DONE]\n\n'))};try{const rows=[];for await(const e of new CompatibleProvider(config).streamChat({messages:[]}))rows.push(e);assert.equal(rows.at(-1).result.text,'你好');assert.equal(rows.at(-1).result.usage.total_tokens,3);assert.equal(options.credentials,'omit');assert.equal(options.redirect,'error')}finally{globalThis.fetch=old}});
test('truncated stream keeps yielded text but reports interruption',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>new Response(stream('data: {"choices":[{"delta":{"content":"partial"}}]}\n\n'));const rows=[];try{await assert.rejects(async()=>{for await(const e of new CompatibleProvider(config).streamChat({messages:[]}))rows.push(e)},e=>e.code==='interrupted');assert.equal(rows[0].text,'partial')}finally{globalThis.fetch=old}});
test('provider failures redact API key and custom header secrets',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>new Response('bad test-secret-not-real private-header Bearer hidden',{status:401});try{await assert.rejects(new CompatibleProvider(config).chat({messages:[]}),e=>e.code==='auth'&&!e.detail.includes('test-secret')&&!e.detail.includes('private-header')&&!e.detail.includes('hidden'))}finally{globalThis.fetch=old}});
test('unsafe remote endpoint forms fail before credentials are sent',()=>{for(const baseUrl of ['http://example.com','https://user:pass@example.com','https://example.com?key=x','https://example.com/#x'])assert.throws(()=>endpoint({...config,baseUrl},'/models'));assert.equal(endpoint({...config,baseUrl:'http://127.0.0.1:1234/v1/'},'/models'),'http://127.0.0.1:1234/v1/models')});
test('non-streaming fallback yields the same adapter contract',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({choices:[{message:{content:'complete'}}]});try{const rows=[];for await(const e of new CompatibleProvider({...config,streaming:false}).streamChat({messages:[]}))rows.push(e);assert.deepEqual(rows.map(r=>r.type),['delta','done'])}finally{globalThis.fetch=old}});
test('reasoning-only budget exhaustion is not a network interruption',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>new Response(stream('data: {"choices":[{"delta":{"content":""}}]}\n\ndata: {"choices":[{"delta":{},"finish_reason":"length"}],"usage":{"completion_tokens":64,"completion_tokens_details":{"reasoning_tokens":64}}}\n\ndata: [DONE]\n\n'));const rows=[];try{await assert.rejects(async()=>{for await(const e of new CompatibleProvider(config).streamChat({messages:[]}))rows.push(e)},e=>e.code==='outputLimit'&&e.output.reasoningTokens===64);assert.equal(rows.length,0)}finally{globalThis.fetch=old}});
test('empty resolver response cannot masquerade as a valid decision',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({choices:[{message:{content:''},finish_reason:'length'}],usage:{completion_tokens:64,completion_tokens_details:{reasoning_tokens:64}}});try{await assert.rejects(new CompatibleProvider(config).chat({messages:[],purpose:'resolver'}),e=>e.code==='outputLimit'&&e.output.completionTokens===64)}finally{globalThis.fetch=old}});
test('partial length-limited reply is preserved but not completed',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>new Response(stream('data: {"choices":[{"delta":{"content":"partial"},"finish_reason":"length"}]}\n\ndata: [DONE]\n\n'));const rows=[];try{await assert.rejects(async()=>{for await(const e of new CompatibleProvider(config).streamChat({messages:[]}))rows.push(e)},e=>e.code==='outputLimit');assert.equal(rows[0].text,'partial');assert.equal(rows.length,1)}finally{globalThis.fetch=old}});

test('GLM resolver disables thinking only on verified service hosts',()=>{const req={purpose:'resolver',messages:[]},c={...config,model:'glm-5.2'};assert.deepEqual(resolverOptions({...c,baseUrl:'https://dashscope.aliyuncs.com/compatible-mode/v1'},req),{enable_thinking:false});assert.deepEqual(resolverOptions({...c,baseUrl:'https://open.bigmodel.cn/api/paas/v4'},req),{thinking:{type:'disabled'}});assert.deepEqual(resolverOptions({...c,baseUrl:'https://proxy.example/v1'},req),{});assert.deepEqual(resolverOptions({...c,baseUrl:'https://dashscope.aliyuncs.com/compatible-mode/v1'},{messages:[]}),{});assert.deepEqual(resolverOptions({...c,model:'glm-5.3',baseUrl:'https://open.bigmodel.cn/api/paas/v4'},req),{})});
